[package]
name = "elden-ring-save-parser"
version = "0.1.0"
authors = ["EthanShoeDev <13422990+EthanShoeDev@users.noreply.github.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]
console_error_panic_hook = ["dep:console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
aes = "0.8.4"
cbc = "0.1.2"
binary-reader = "0.4.5"
once_cell = "1.19.0"
md5 = "0.7.0"
encoding_rs = "0.8.34"
miniz_oxide = "0.7.4"
bitflags = "2.5.0"
strsim = "0.11.1"
serde-wasm-bindgen = "0.6.5"
serde = { version = "1.0.203", features = ["derive"] }
web-sys = { version = "0.3.69", features = ["console"] }
serde_bytes = "0.11.15"
serde_json = "=1.0.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
