import { recommended as effectTsgoRecommended } from '@effect/tsgo/oxlint-presets';
import { defineConfig } from 'oxlint';

// Effect diagnostics are reported by oxlint (via the `effect-tsgo patch --oxlint`
// prepare step), not by the language service, so the whole preset lands at
// `error` like every other rule here. Deriving the map from the preset keeps new
// rules enforced when @effect/tsgo is upgraded rather than silently landing at
// the preset's `warn`. Per-rule opt-outs live in `rules` below.
const effectTsgoRules = Object.fromEntries(
  Object.keys(effectTsgoRecommended.rules ?? {}).map((rule) => [rule, 'error']),
);

export default defineConfig({
  extends: [effectTsgoRecommended],
  plugins: [
    'eslint',
    'typescript',
    'unicorn',
    'oxc',
    'import',
    'jsdoc',
    'node',
    'promise',
    'react',
    'react-perf',
    'jsx-a11y',
  ],
  // Custom JS plugins built from packages/config/oxlint-plugins. They are referenced
  // by their package export paths and resolved through the bun workspace.
  jsPlugins: [
    '@elden-ring-compass/oxlint-plugins/require-disable-description',
    '@elden-ring-compass/oxlint-plugins/forbidden-unknown-cast',
    '@elden-ring-compass/oxlint-plugins/prefer-effect',
  ],
  env: {
    browser: true,
  },
  categories: {
    correctness: 'error',
    perf: 'error',
    suspicious: 'error',
  },
  ignorePatterns: [
    'docs/cloned-repos-as-docs/**',
    '**/dist/**',
    '**/pkg/**',
    '**/.output/**',
    '**/.nitro/**',
    '**/.turbo/**',
    '**/*.gen.*',
    '**/routeTree.gen.ts',
    '**/*.vendored.*',
    // Generated game data from the erdb project; not hand-linted.
    'apps/web/src/assets/erdb/**',
    'apps/web/src/lib/elden-ring-raw-db/**',
    // Generated by @elden-ring-compass/extractor (codegen stage).
    'packages/data/src/generated/**',
    // shadcn/ui components are vendored from the registry; we don't hand-lint them.
    '**/components/ui/**',
    // Rust/WASM build output and git submodule.
    'packages/elden-ring-save-parser/pkg/**',
    'packages/ER-Save-Editor/**',
    'CLAUDE.md',
    '.agents/**',
    '.claude/skills/**',
    '.cursor/**',
    '.opencode/**',
    '.github/skills/**',
  ],
  /*
   * When we deviate from a default, leave a comment explaining why.
   * Do not add a rule without a comment.
   */
  rules: {
    // Effect.gen generators yield* as the final expression; oxlint reads that
    // as a missing return. Off across the repo.
    'typescript/consistent-return': 'off',
    // oxfmt owns import ordering.
    'sort-imports': 'off',
    // Default-exported configs/routes are idiomatic here (vite, tanstack).
    'import/no-default-export': 'off',
    // We use the automatic JSX runtime (jsx: 'react-jsx'), so React does not
    // need to be imported into scope.
    'react/react-in-jsx-scope': 'off',
    // Rules of React enforcement for the React Compiler. oxlint has no
    // `react-compiler` plugin (it doesn't exist), and `rules-of-hooks` is OFF by
    // default — it is not part of the `correctness` category. The compiler
    // silently bails out of any component that breaks the Rules of Hooks, so we
    // promote it to an error to catch those at lint time rather than losing the
    // optimization at build time. (`react/exhaustive-deps`, the other rule the
    // compiler relies on, is already on via the `correctness` category.)
    'react/rules-of-hooks': 'error',
    // Type-aware assertions are used deliberately at JSON/ESLint-AST
    // boundaries (catalog-check, the oxlint plugins). `unknown-cast/forbidden`
    // already guards the dangerous `as unknown as` form with a required reason.
    'typescript/no-unsafe-type-assertion': 'off',
    // The non-null assertion (`!`) silently bypasses strict null checks. Narrow
    // with Effect instead: `Option.fromNullable(x)` + `Option.match`/`getOrElse`,
    // `Predicate.isNotNullable`, or `effect/Schema` for validated parsing. (The
    // old `assertDefined` throwing helper is deprecated — don't reach for it.)
    'typescript/no-non-null-assertion': 'error',

    // --- Rule deviations mirrored from the reference monorepos (fressh,
    // listening-astro). These fire pervasively and were judged not worth
    // enforcing there; we keep parity so the configs stay portable. ---
    // Sequential `await` in a loop is frequently intentional here (ordered IO,
    // backpressure in the archive unpackers) — not a perf bug. Disabled in
    // listening-astro for the same reason.
    'no-await-in-loop': 'off',
    // react-perf flags every inline handler/object/array prop. That is
    // premature optimization; rely on the React Compiler / profiling instead.
    'react-perf/jsx-no-new-function-as-prop': 'off',
    'react-perf/jsx-no-new-object-as-prop': 'off',
    'react-perf/jsx-no-new-array-as-prop': 'off',
    'react-perf/jsx-no-jsx-as-prop': 'off',
    // Shadowing an outer name in a nested scope (e.g. `state`) is readable here.
    'no-shadow': 'off',
    // Leading/trailing underscores mark intentionally-unused bindings.
    'no-underscore-dangle': 'off',
    // CSS and test-setup side-effect imports have no binding to assign.
    'import/no-unassigned-import': 'off',
    // Index keys are acceptable for the static, non-reordered lists used here.
    'react/no-array-index-key': 'off',
    // Small helper closures are fine where they are defined.
    'unicorn/consistent-function-scoping': 'off',
    // Web Workers' postMessage takes a transfer list, not a targetOrigin. This
    // unicorn rule targets cross-window `window.postMessage` and is a false
    // positive for the save-parser worker (`self.postMessage`/`worker.postMessage`).
    'unicorn/require-post-message-target-origin': 'off',
    // Spreading inside map() is idiomatic for the view-model builders.
    'oxc/no-map-spread': 'off',
    // Not every then() callback needs to return a value.
    'promise/always-return': 'off',
    // Memoizing every context value is not required for this app.
    'react/jsx-no-constructed-context-values': 'off',

    // --- Effect rules (@effect/tsgo oxlint preset), all elevated to error ---
    ...effectTsgoRules,
    // The rules the Effect language service ships `off` stay off here too:
    // enabling one is a deliberate opt-in, not a side effect of adopting the
    // preset (which turns several of them on) or of the blanket `categories`
    // severities above (which turn on every `effecttsgo` rule in those
    // categories, preset or not). `prefer-schema-over-json` is the one this
    // repo opted into (it was `error` in the old tsconfig plugin config), so it
    // is absent from this list and stays at error.
    'effecttsgo/any-unknown-in-error-context': 'off',
    'effecttsgo/async-function': 'off',
    'effecttsgo/crypto-random-uuid': 'off',
    'effecttsgo/crypto-random-uuid-in-effect': 'off',
    'effecttsgo/deterministic-keys': 'off',
    'effecttsgo/effect-do-notation': 'off',
    'effecttsgo/extends-native-error': 'off',
    'effecttsgo/global-console': 'off',
    'effecttsgo/global-console-in-effect': 'off',
    'effecttsgo/global-date': 'off',
    'effecttsgo/global-date-in-effect': 'off',
    'effecttsgo/global-fetch': 'off',
    'effecttsgo/global-fetch-in-effect': 'off',
    'effecttsgo/global-random': 'off',
    'effecttsgo/global-random-in-effect': 'off',
    'effecttsgo/global-timers': 'off',
    'effecttsgo/global-timers-in-effect': 'off',
    'effecttsgo/instance-of-schema': 'off',
    'effecttsgo/missed-pipeable-opportunity': 'off',
    'effecttsgo/missing-effect-service-dependency': 'off',
    'effecttsgo/missing-pipeable-signature': 'off',
    'effecttsgo/nested-effect-gen-yield': 'off',
    'effecttsgo/new-promise': 'off',
    'effecttsgo/new-schema-class': 'off',
    'effecttsgo/node-builtin-import': 'off',
    'effecttsgo/prefer-schema-type-property': 'off',
    'effecttsgo/process-env': 'off',
    'effecttsgo/process-env-in-effect': 'off',
    'effecttsgo/schema-sync': 'off',
    'effecttsgo/schema-union-of-literals': 'off',
    'effecttsgo/service-not-as-class': 'off',
    'effecttsgo/strict-boolean-expressions': 'off',
    'effecttsgo/strict-effect-provide': 'off',
    'effecttsgo/unnecessary-arrow-block': 'off',
    'effecttsgo/unsafe-effect-type-assertion': 'off',
    // Suggestion-level in the language service (never gated the old `tsc`
    // typecheck). Every `Schema.Number` in the extractor/data/share schemas
    // trips it (216 on adoption); switching them to `Schema.Finite` changes
    // decode semantics (rejects NaN/±Infinity), so that is its own change.
    'effecttsgo/schema-number': 'off',

    // ─── Newly default at oxlint 1.82 ───────────────────────────────────
    // React Compiler-derived rules the bump from 1.68 turned on by way of the
    // blanket `categories` severities above. Held off so the toolchain bump
    // stays behaviour-neutral; adopting any of them is its own change (the
    // compiler already bails out of the flagged components at build time).
    // Counts are the 1.82 first-run totals.
    'react/set-state-in-effect': 'off', // 7 - theme/mobile/map/share sync-from-external-state effects
    'react/preserve-manual-memoization': 'off', // 1 - leaflet-map useMemo
    'react/incompatible-library': 'off', // 1 - data-table (TanStack Table row APIs)

    // --- Custom plugin rules ---
    // Disable directives (eslint-disable / @ts-expect-error) must carry a reason.
    'disable-comments/require-description': 'error',
    // `as unknown as` double-casts bypass the type system; opt in explicitly.
    'unknown-cast/forbidden': 'error',
    // Prefer @effect/platform over raw node:fs / node:path.
    'prefer-effect/no-node-path': 'error',
    'prefer-effect/no-node-fs': 'error',
  },
  overrides: [
    {
      // Config files, scripts, and the oxlint plugins themselves legitimately
      // touch the filesystem and use default exports.
      files: [
        'scripts/**',
        'packages/config/oxlint-plugins/**',
        '**/*.config.{ts,js,mjs}',
        'oxlint.config.ts',
      ],
      rules: {
        'prefer-effect/no-node-path': 'off',
        'prefer-effect/no-node-fs': 'off',
        'no-console': 'off',
      },
    },
    {
      // Tests, benchmarks, and build-time tooling (vite plugins, per-package
      // maintenance scripts) legitimately read files with `node:fs`/`node:path`
      // — `prefer-effect` targets runtime/library code, not a fixture read in a
      // test or a one-shot script.
      files: [
        '**/*.test.ts',
        '**/*.bench.ts',
        '**/perf/**',
        '**/vite-plugins/**',
        '**/scripts/**',
      ],
      rules: {
        'prefer-effect/no-node-path': 'off',
        'prefer-effect/no-node-fs': 'off',
        'no-console': 'off',
      },
    },
  ],
});
