export const GRACES: Record<
  string,
  Record<string, [string, number, string]>
> = {
  'Table of Lost Grace / Roundtable Hold': {
    RoundtableHold: [
      'RoundtableHold',
      71190,
      'Table of Lost Grace / Roundtable Hold',
    ],
  },
  Limgrave: {
    AgheelLakeNorth: ['Limgrave', 76108, 'Agheel Lake North'],
    AgheelLakeSouth: ['Limgrave', 76106, 'Agheel Lake South'],
    ChurchofDragonCommunion: ['Limgrave', 76110, 'Church of Dragon Communion'],
    ChurchofElleh: ['Limgrave', 76100, 'Church of Elleh'],
    CoastalCave: ['Limgrave', 73115, 'Coastal Cave'],
    FortHaightWest: ['Limgrave', 76105, 'Fort Haight West'],
    Gatefront: ['Limgrave', 76111, 'Gatefront'],
    GrovesideCave: ['Limgrave', 73103, 'Groveside Cave'],
    HighroadCave: ['Limgrave', 73117, 'Highroad Cave'],
    LimgraveArtistShack: ['Limgrave', 76103, "Artist's Shack (Limgrave)"],
    LimgraveTunnels: ['Limgrave', 73201, 'Limgrave Tunnels'],
    MistwoodOutskirts: ['Limgrave', 76114, 'Mistwood Outskirts'],
    MurkwaterCatacombs: ['Limgrave', 73004, 'Murkwater Catacombs'],
    MurkwaterCave: ['Limgrave', 73100, 'Murkwater Cave'],
    MurkwaterCoast: ['Limgrave', 76116, 'Murkwater Coast'],
    SeasideRuins: ['Limgrave', 76113, 'Seaside Ruins'],
    StormfootCatacombs: ['Limgrave', 73002, 'Stormfoot Catacombs'],
    SummonwaterVillageOutskirts: [
      'Limgrave',
      76119,
      'Summonwater Village Outskirts',
    ],
    TheFirstStep: ['Limgrave', 76101, 'The First Step'],
    ThirdChurchofMarika: ['Limgrave', 76104, 'Third Church of Marika'],
    WaypointRuinsCellar: ['Limgrave', 76120, 'Waypoint Ruins Cellar'],
  },
  'Stranded Graveyard': {
    CaveofKnowledge: ['StrandedGraveyard', 71800, 'Cave of Knowledge'],
    StrandedGraveyard: ['StrandedGraveyard', 71801, 'Stranded Graveyard'],
  },
  Stormhill: {
    CastlewardTunnel: ['Stormhill', 71002, 'Castleward Tunnel'],
    DeathtouchedCatacombs: ['Stormhill', 73011, 'Deathtouched Catacombs'],
    DivineTowerofLimgrave: ['Stormhill', 73412, 'Divine Tower of Limgrave'],
    LimgraveTowerBridge: ['Stormhill', 73410, 'Limgrave Tower Bridge'],
    MargittheFellOmen: ['Stormhill', 71001, 'Margit, the Fell Omen'],
    Saintsbridge: ['Stormhill', 76117, 'Saintsbridge'],
    StormhillShack: ['Stormhill', 76102, 'Stormhill Shack'],
    WarmastersShack: ['Stormhill', 76118, "Warmaster's Shack"],
  },
  'Weeping Peninsula': {
    AilingVillageOutskirts: [
      'WeepingPeninsula',
      76154,
      'Ailing Village Outskirts',
    ],
    BehindTheCastle: ['WeepingPeninsula', 76159, 'Behind The Castle'],
    BesidetheCraterPockedGlade: [
      'WeepingPeninsula',
      76155,
      'Beside the Crater-Pocked Glade',
    ],
    BesidetheRampartGaol: [
      'WeepingPeninsula',
      76160,
      'Beside the Rampart Gaol',
    ],
    BridgeofSacrifice: ['WeepingPeninsula', 76157, 'Bridge of Sacrifice'],
    CastleMorneLift: ['WeepingPeninsula', 76158, 'Castle Morne Lift'],
    CastleMorneRampart: ['WeepingPeninsula', 76151, 'Castle Morne Rampart'],
    ChurchofPilgrimage: ['WeepingPeninsula', 76150, 'Church of Pilgrimage'],
    EarthboreCave: ['WeepingPeninsula', 73101, 'Earthbore Cave'],
    FourthChurchofMarika: [
      'WeepingPeninsula',
      76162,
      'Fourth Church of Marika',
    ],
    ImpalersCatacombs: ['WeepingPeninsula', 73001, "Impaler's Catacombs"],
    LimgraveIsolatedMerchantsShack: [
      'WeepingPeninsula',
      76156,
      "Isolated Merchant's Shack (Limgrave)",
    ],
    MorneMoangrave: ['WeepingPeninsula', 76161, 'Morne Moangrave'],
    MorneTunnel: ['WeepingPeninsula', 73200, 'Morne Tunnel'],
    SouthoftheLookoutTower: [
      'WeepingPeninsula',
      76153,
      'South of the Lookout Tower',
    ],
    Tombsward: ['WeepingPeninsula', 76152, 'Tombsward'],
    TombswardCatacombs: ['WeepingPeninsula', 73000, 'Tombsward Catacombs'],
    TombswardCave: ['WeepingPeninsula', 73102, 'Tombsward Cave'],
  },
  'Stormveil Castle': {
    GatesideChamber: ['StormveilCastle', 71003, 'Gateside Chamber'],
    GodricktheGrafted: ['StormveilCastle', 71000, 'Godrick the Grafted'],
    LiftsideChamber: ['StormveilCastle', 71006, 'Liftside Chamber'],
    RampartTower: ['StormveilCastle', 71005, 'Rampart Tower'],
    SecludedCell: ['StormveilCastle', 71007, 'Secluded Cell'],
    StormveilCliffside: ['StormveilCastle', 71004, 'Stormveil Cliffside'],
    StormveilMainGate: ['StormveilCastle', 71008, 'Stormveil Main Gate'],
  },
  'Liurnia of the Lakes': {
    AcademyCrystalCave: ['LiurniaOfTheLakes', 73106, 'Academy Crystal Cave'],
    AcademyGateTown: ['LiurniaOfTheLakes', 76204, 'Academy Gate Town'],
    BehindCariaManor: ['LiurniaOfTheLakes', 76238, 'Behind Caria Manor'],
    BlackKnifeCatacombs: ['LiurniaOfTheLakes', 73005, 'Black Knife Catacombs'],
    BoilprawnShack: ['LiurniaOfTheLakes', 76216, 'Boilprawn Shack'],
    ChurchofVows: ['LiurniaOfTheLakes', 76224, 'Church of Vows'],
    CliffbottomCatacombs: ['LiurniaOfTheLakes', 73006, 'Cliffbottom Catacombs'],
    ConvertedTower: ['LiurniaOfTheLakes', 76237, 'Converted Tower'],
    CrystallineWoods: ['LiurniaOfTheLakes', 76243, 'Crystalline Woods'],
    DivineTowerofLiurnia: [
      'LiurniaOfTheLakes',
      73422,
      'Divine Tower of Liurnia',
    ],
    EasternLiurniaLakeShore: [
      'LiurniaOfTheLakes',
      76223,
      'Eastern Liurnia Lake Shore',
    ],
    EasternTableland: ['LiurniaOfTheLakes', 76234, 'Eastern Tableland'],
    EastGateBridgeTrestle: [
      'LiurniaOfTheLakes',
      76242,
      'East Gate Bridge Trestle',
    ],
    FallenRuinsoftheLake: [
      'LiurniaOfTheLakes',
      76236,
      'Fallen Ruins of the Lake',
    ],
    FollyontheLake: ['LiurniaOfTheLakes', 76219, 'Folly on the Lake'],
    FootoftheFourBelfries: [
      'LiurniaOfTheLakes',
      76210,
      'Foot of the Four Belfries',
    ],
    GateTownBridge: ['LiurniaOfTheLakes', 76222, 'Gate Town Bridge'],
    GateTownNorth: ['LiurniaOfTheLakes', 76233, 'Gate Town North'],
    Jarburg: ['LiurniaOfTheLakes', 76245, 'Jarburg'],
    LakeFacingCliffs: ['LiurniaOfTheLakes', 76200, 'Lake-Facing Cliffs'],
    LakesideCrystalCave: ['LiurniaOfTheLakes', 73105, 'Lakeside Crystal Cave'],
    LaskyarRuins: ['LiurniaOfTheLakes', 76202, 'Laskyar Ruins'],
    LiurniaHighwayNorth: ['LiurniaOfTheLakes', 76221, 'Liurnia Highway North'],
    LiurniaHighwaySouth: ['LiurniaOfTheLakes', 76244, 'Liurnia Highway South'],
    LiurniaLakeShore: ['LiurniaOfTheLakes', 76201, 'Liurnia Lake Shore'],
    LiurniaoftheLakesArtistsShack: [
      'LiurniaOfTheLakes',
      76217,
      "Artist's Shack (Liurnia of the Lakes)",
    ],
    LiurniaTowerBridge: ['LiurniaOfTheLakes', 73421, 'Liurnia Tower Bridge'],
    MainAcademyGate: ['LiurniaOfTheLakes', 76206, 'Main Academy Gate'],
    MainCariaManorGate: ['LiurniaOfTheLakes', 76214, 'Main Caria Manor Gate'],
    ManorLowerLevel: ['LiurniaOfTheLakes', 76231, 'Manor Lower Level'],
    ManorUpperLevel: ['LiurniaOfTheLakes', 76230, 'Manor Upper Level'],
    MausoleumCompound: ['LiurniaOfTheLakes', 76226, 'Mausoleum Compound'],
    NorthernLiurniaLakeShore: [
      'LiurniaOfTheLakes',
      76212,
      'Northern Liurnia Lake Shore',
    ],
    RannisChamber: ['LiurniaOfTheLakes', 76247, "Ranni's Chamber"],
    RannisRise: ['LiurniaOfTheLakes', 76228, "Ranni's Rise"],
    RavineVeiledVillage: ['LiurniaOfTheLakes', 76229, 'Ravine-Veiled Village'],
    RayaLucariaCrystalTunnel: [
      'LiurniaOfTheLakes',
      73202,
      'Raya Lucaria Crystal Tunnel',
    ],
    RevengersShack: ['LiurniaOfTheLakes', 76218, "Revenger's Shack"],
    RoadsEndCatacombs: ['LiurniaOfTheLakes', 73003, "Road's End Catacombs"],
    RoadtotheManor: ['LiurniaOfTheLakes', 76213, 'Road to the Manor'],
    RoyalMoongazingGrounds: [
      'LiurniaOfTheLakes',
      76232,
      'Royal Moongazing Grounds',
    ],
    RuinedLabyrinth: ['LiurniaOfTheLakes', 76225, 'Ruined Labyrinth'],
    ScenicIsle: ['LiurniaOfTheLakes', 76203, 'Scenic Isle'],
    SlumberingWolfsShack: [
      'LiurniaOfTheLakes',
      76215,
      "Slumbering Wolf's Shack",
    ],
    SorcerersIsle: ['LiurniaOfTheLakes', 76211, "Sorcerer's Isle"],
    SouthRayaLucariaGate: [
      'LiurniaOfTheLakes',
      76205,
      'South Raya Lucaria Gate',
    ],
    StillwaterCave: ['LiurniaOfTheLakes', 73104, 'Stillwater Cave'],
    StudyHallEntrance: ['LiurniaOfTheLakes', 73420, 'Study Hall Entrance'],
    TempleQuarter: ['LiurniaOfTheLakes', 76241, 'Temple Quarter'],
    TheFourBelfries: ['LiurniaOfTheLakes', 76227, 'The Four Belfries'],
    TheRavine: ['LiurniaOfTheLakes', 76235, 'The Ravine'],
    VillageoftheAlbinaurics: [
      'LiurniaOfTheLakes',
      76220,
      'Village of the Albinaurics',
    ],
  },
  'Bellum Highway': {
    BellumChurch: ['BellumHighway', 76208, 'Bellum Church'],
    ChurchofInhibition: ['BellumHighway', 76240, 'Church of Inhibition'],
    EastRayaLucariaGate: ['BellumHighway', 76207, 'East Raya Lucaria Gate'],
    FrenziedFlameVillageOutskirts: [
      'BellumHighway',
      76239,
      'Frenzied Flame Village Outskirts',
    ],
    GrandLiftofDectus: ['BellumHighway', 76209, 'Grand Lift of Dectus'],
  },
  'Ruin-Strewn Precipice': {
    MagmaWyrm: ['RuinStrewnPrecipice', 73900, 'Magma Wyrm'],
    RuinStrewnPrecipice: [
      'RuinStrewnPrecipice',
      73901,
      'Ruin-Strewn Precipice',
    ],
    RuinStrewnPrecipiceOverlook: [
      'RuinStrewnPrecipice',
      73902,
      'Ruin-Strewn Precipice Overlook',
    ],
  },
  'Moonlight Altar': {
    AltarSouth: ['MoonlightAltar', 76252, 'Altar South'],
    CathedralofManusCeles: [
      'MoonlightAltar',
      76251,
      'Cathedral of Manus Celes',
    ],
    MoonlightAltar: ['MoonlightAltar', 76250, 'Moonlight Altar'],
  },
  'Academy of Raya Lucaria': {
    ChurchoftheCuckoo: ['AcademyOfRayaLucaria', 71402, 'Church of the Cuckoo'],
    DebateParlour: ['AcademyOfRayaLucaria', 71401, 'Debate Parlour'],
    RayaLucariaGrandLibrary: [
      'AcademyOfRayaLucaria',
      71400,
      'Raya Lucaria Grand Library',
    ],
    SchoolhouseClassroom: [
      'AcademyOfRayaLucaria',
      71403,
      'Schoolhouse Classroom',
    ],
  },
  'Altus Plateau': {
    AbandonedCoffin: ['AltusPlateau', 76300, 'Abandoned Coffin'],
    AltusHighwayJunction: ['AltusPlateau', 76303, 'Altus Highway Junction'],
    AltusPlateau: ['AltusPlateau', 76301, 'Altus Plateau'],
    AltusTunnel: ['AltusPlateau', 73205, 'Altus Tunnel'],
    BowerofBounty: ['AltusPlateau', 76306, 'Bower of Bounty'],
    CastellansHall: ['AltusPlateau', 76322, "Castellan's Hall"],
    ErdtreeGazingHill: ['AltusPlateau', 76302, 'Erdtree-Gazing Hill'],
    ForestSpanningGreatbridge: [
      'AltusPlateau',
      76304,
      'Forest-Spanning Greatbridge',
    ],
    OldAltusTunnel: ['AltusPlateau', 73204, 'Old Altus Tunnel'],
    PerfumersGrotto: ['AltusPlateau', 73118, "Perfumer's Grotto"],
    RampartsidePath: ['AltusPlateau', 76305, 'Rampartside Path'],
    RoadofIniquitySidePath: [
      'AltusPlateau',
      76307,
      'Road of Iniquity Side Path',
    ],
    SagesCave: ['AltusPlateau', 73119, "Sage's Cave"],
    SaintedHerosGrave: ['AltusPlateau', 73008, "Sainted Hero's Grave"],
    ShadedCastleInnerGate: ['AltusPlateau', 76321, 'Shaded Castle Inner Gate'],
    ShadedCastleRamparts: ['AltusPlateau', 76320, 'Shaded Castle Ramparts'],
    UnsightlyCatacombs: ['AltusPlateau', 73012, 'Unsightly Catacombs'],
    WindmillHeights: ['AltusPlateau', 76313, 'Windmill Heights'],
    WindmillVillage: ['AltusPlateau', 76308, 'Windmill Village'],
  },
  'Mt. Gelmir': {
    BridgeofIniquity: ['MtGelmir', 76350, 'Bridge of Iniquity'],
    CraftsmansShack: ['MtGelmir', 76356, "Craftsman's Shack"],
    FirstMtGelmirCampsite: ['MtGelmir', 76351, 'First Mt. Gelmir Campsite'],
    GelmirHerosGrave: ['MtGelmir', 73009, "Gelmir Hero's Grave"],
    NinthMtGelmirCampsite: ['MtGelmir', 76352, 'Ninth Mt. Gelmir Campsite'],
    PrimevalSorcererAzur: ['MtGelmir', 76357, 'Primeval Sorcerer Azur'],
    RoadofIniquity: ['MtGelmir', 76353, 'Road of Iniquity'],
    SeethewaterCave: ['MtGelmir', 73107, 'Seethewater Cave'],
    SeethewaterRiver: ['MtGelmir', 76354, 'Seethewater River'],
    SeethewaterTerminus: ['MtGelmir', 76355, 'Seethewater Terminus'],
    VolcanoCave: ['MtGelmir', 73109, 'Volcano Cave'],
    WyndhamCatacombs: ['MtGelmir', 73007, 'Wyndham Catacombs'],
  },
  'Capital Outskirts': {
    AurizaSideTomb: ['CapitalOutskirts', 73013, 'Auriza Side Tomb'],
    AuziraHerosGrave: ['CapitalOutskirts', 73010, "Auzira Hero's Grave"],
    CapitalRampart: ['CapitalOutskirts', 76314, 'Capital Rampart'],
    DivineTowerofWestAltus: [
      'CapitalOutskirts',
      73430,
      'Divine Tower of West Altus',
    ],
    DivineTowerofWestAltusGate: [
      'CapitalOutskirts',
      73432,
      'Divine Tower of West Altus: Gate',
    ],
    HermitMerchantsShack: [
      'CapitalOutskirts',
      76311,
      "Hermit Merchant's Shack",
    ],
    MinorEerdtreeChurch: ['CapitalOutskirts', 76310, 'Minor Eerdtree Church'],
    OuterWallBattleground: [
      'CapitalOutskirts',
      76312,
      'Outer Wall Battleground',
    ],
    OuterWallPhantomTree: [
      'CapitalOutskirts',
      76309,
      'Outer Wall Phantom Tree',
    ],
    SealedTunnel: ['CapitalOutskirts', 73431, 'Sealed Tunnel'],
  },
  'Volcano Manor': {
    AbductorVirgin: ['VolcanoManor', 71606, 'Abductor Virgin'],
    AudiencePathway: ['VolcanoManor', 71605, 'Audience Pathway'],
    GuestHall: ['VolcanoManor', 71604, 'Guest Hall'],
    PrisonTownChurch: ['VolcanoManor', 71603, 'Prison Town Church'],
    RykardLordofBlasphemy: ['VolcanoManor', 71600, 'Rykard, Lord of Blasphemy'],
    SubterraneanInquisitionChamber: [
      'VolcanoManor',
      71607,
      'Subterranean Inquisition Chamber',
    ],
    TempleofEiglay: ['VolcanoManor', 71601, 'Temple of Eiglay'],
    VolcanoManor: ['VolcanoManor', 71602, 'Volcano Manor'],
  },
  'Leyndell, Royal Capital': {
    AvenueBalcony: ['LeyndellRoyalCapital', 71104, 'Avenue Balcony'],
    DivineBridge: ['LeyndellRoyalCapital', 71109, 'Divine Bridge'],
    EastCapitalRampart: ['LeyndellRoyalCapital', 71102, 'East Capital Rampart'],
    EldenThrone: ['LeyndellRoyalCapital', 71100, 'Elden Throne'],
    ErdtreeSanctuary: ['LeyndellRoyalCapital', 71101, 'Erdtree Sanctuary'],
    FortifiedManorFirstFloor: [
      'LeyndellRoyalCapital',
      71108,
      'Fortified Manor, First Floor',
    ],
    LowerCapitalChurch: ['LeyndellRoyalCapital', 71103, 'Lower Capital Church'],
    QueensBedchamber: ['LeyndellRoyalCapital', 71107, "Queen's Bedchamber"],
    WestCapitalRampart: ['LeyndellRoyalCapital', 71105, 'West Capital Rampart'],
  },
  'Subterranean Shunning-Grounds': {
    CathedraloftheForsaken: [
      'SubterraneanShunningGrounds',
      73500,
      'Cathedral of the Forsaken',
    ],
    ForsakenDepths: ['SubterraneanShunningGrounds', 73502, 'Forsaken Depths'],
    FrenziedFlameProscription: [
      'SubterraneanShunningGrounds',
      73504,
      'Frenzied Flame Proscription',
    ],
    LeyndellCatacombs: [
      'SubterraneanShunningGrounds',
      73503,
      'Leyndell Catacombs',
    ],
    UndergroundRoadside: [
      'SubterraneanShunningGrounds',
      73501,
      'Underground Roadside',
    ],
  },
  'Leyndell, Ashen Capital': {
    LeyendellCapitalofAsh: [
      'LeyndellAshenCapital',
      71123,
      'Leyendell, Capital of Ash',
    ],
    LeyndellAshenCapitalDivineBridge: [
      'LeyndellAshenCapital',
      71125,
      'Divine Bridge',
    ],
    LeyndellAshenCapitalEastCapitalRampart: [
      'LeyndellAshenCapital',
      71122,
      'East Capital Rampart',
    ],
    LeyndellAshenCapitalEldenThrone: [
      'LeyndellAshenCapital',
      71120,
      'Elden Throne',
    ],
    LeyndellAshenCapitalErdtreeSanctuary: [
      'LeyndellAshenCapital',
      71121,
      'Erdtree Sanctuary',
    ],
    LeyndellAshenCapitalQueensBedchamber: [
      'LeyndellAshenCapital',
      71124,
      "Queen's Bedchamber",
    ],
  },
  'Stone Platfrom': {
    FracturedMarika: ['StonePlatform', 71900, 'Fractured Marika'],
  },
  Caelid: {
    AbandonedCave: ['Caelid', 73120, 'Abandoned Cave'],
    CaelemRuins: ['Caelid', 76403, 'Caelem Ruins'],
    CaelidCatacombs: ['Caelid', 73015, 'Caelid Catacombs'],
    CaelidHighwaySouth: ['Caelid', 76405, 'Caelid Highway South'],
    CathedralofDragonCommunion: [
      'Caelid',
      76404,
      'Cathedral of Dragon Communion',
    ],
    ChairCryptofSellia: ['Caelid', 76415, 'Chair-Crypt of Sellia'],
    ChamberOutsidethePlaza: ['Caelid', 76420, 'Chamber Outside the Plaza'],
    ChurchofthePlague: ['Caelid', 76418, 'Church of the Plague'],
    DeepSiofraWell: ['Caelid', 76410, 'Deep Siofra Well'],
    FortGaelNorth: ['Caelid', 76402, 'Fort Gael North'],
    GaelTunnel: ['Caelid', 73207, 'Gael Tunnel'],
    GaolCave: ['Caelid', 73121, 'Gaol Cave'],
    ImpassableGreatbridge: ['Caelid', 76417, 'Impassable Greatbridge'],
    MinorEerdtreeCatacombs: ['Caelid', 73014, 'Minor Eerdtree Catacombs'],
    RearGaelTunnelEntrance: ['Caelid', 73257, 'Rear Gael Tunnel Entrance'],
    RedmaneCastlePlaza: ['Caelid', 76419, 'Redmane Castle Plaza'],
    RotviewBalcony: ['Caelid', 76401, 'Rotview Balcony'],
    SelliaBackstreets: ['Caelid', 76414, 'Sellia Backstreets'],
    SelliaCrystalTunnel: ['Caelid', 73208, 'Sellia Crystal Tunnel'],
    SelliaUnderStair: ['Caelid', 76416, 'Sellia Under-Stair'],
    SmolderingChurch: ['Caelid', 76400, 'Smoldering Church'],
    SmolderingWall: ['Caelid', 76409, 'Smoldering Wall'],
    SouthernAeoniaSwampBank: ['Caelid', 76411, 'Southern Aeonia Swamp Bank'],
    StarscourgeRadahn: ['Caelid', 76422, 'Starscourge Radahn'],
    WarDeadCatacombs: ['Caelid', 73016, 'War-Dead Catacombs'],
  },
  'Swamp of Aeonia': {
    AeoniaSwampShore: ['SwampOfAeonia', 76406, 'Aeonia Swamp Shore'],
    AstrayfromCaelidHighwayNorth: [
      'SwampOfAeonia',
      76407,
      'Astray from Caelid Highway North',
    ],
    HeartofAeonia: ['SwampOfAeonia', 76412, 'Heart of Aeonia'],
    InnerAeonia: ['SwampOfAeonia', 76413, 'Inner Aeonia'],
  },
  "Greyoll's Dragonbarrow": {
    BestialSanctum: ['GreyollsDragonbarrow', 76454, 'Bestial Sanctum'],
    DivineTowerofCaelidBasement: [
      'GreyollsDragonbarrow',
      73440,
      'Divine Tower of Caelid: Basement',
    ],
    DivineTowerofCaelidCenter: [
      'GreyollsDragonbarrow',
      73441,
      'Divine Tower of Caelid: Center',
    ],
    DragonbarrowCave: ['GreyollsDragonbarrow', 73110, 'Dragonbarrow Cave'],
    DragonbarrowFork: ['GreyollsDragonbarrow', 76452, 'Dragonbarrow Fork'],
    DragonbarrowWest: ['GreyollsDragonbarrow', 76450, 'Dragonbarrow West'],
    FarumGreatbridge: ['GreyollsDragonbarrow', 76456, 'Farum Greatbridge'],
    FortFaroth: ['GreyollsDragonbarrow', 76453, 'Fort Faroth'],
    GreyollsDragonbarrowIsolatedMerchantsShack: [
      'GreyollsDragonbarrow',
      76451,
      "Isolated Merchant's Shack (Greyoll's Dragonbarrow)",
    ],
    IsolatedDivineTower: [
      'GreyollsDragonbarrow',
      73460,
      'Isolated Divine Tower',
    ],
    LennesRise: ['GreyollsDragonbarrow', 76455, "Lenne's Rise"],
    SelliaHideaway: ['GreyollsDragonbarrow', 73111, 'Sellia Hideaway'],
  },
  'Forbiden Lands': {
    DivineToweroftheEastAltus: [
      'ForbiddenLands',
      73451,
      'Divine Tower of the East Altus',
    ],
    DivineToweroftheEastAltusGate: [
      'ForbiddenLands',
      73450,
      'Divine Tower of the East Altus: Gate',
    ],
    ForbiddenLands: ['ForbiddenLands', 76500, 'Forbidden Lands'],
    GrandLiftofRold: ['ForbiddenLands', 76502, 'Grand Lift of Rold'],
    HiddenPathtotheHaligtree: [
      'ForbiddenLands',
      73020,
      'Hidden Path to the Haligtree',
    ],
  },
  'Mountaintops of the Giants': {
    AncientSnowValleyRuins: [
      'MountaintopsOfTheGiants',
      76503,
      'Ancient Snow Valley Ruins',
    ],
    CastleSolMainGate: [
      'MountaintopsOfTheGiants',
      76522,
      'Castle Sol Main Gate',
    ],
    CastleSolRooftop: ['MountaintopsOfTheGiants', 76524, 'Castle Sol Rooftop'],
    ChurchoftheEclipse: [
      'MountaintopsOfTheGiants',
      76523,
      'Church of the Eclipse',
    ],
    FirstChurchofMarika: [
      'MountaintopsOfTheGiants',
      76505,
      'First Church of Marika',
    ],
    FreezingLake: ['MountaintopsOfTheGiants', 76504, 'Freezing Lake'],
    SnowValleyRuinsOverlook: [
      'MountaintopsOfTheGiants',
      76521,
      'Snow Valley Ruins Overlook',
    ],
    SpiritcallersCave: [
      'MountaintopsOfTheGiants',
      73122,
      "Spiritcaller's Cave",
    ],
    WhiteridgeRoad: ['MountaintopsOfTheGiants', 76520, 'Whiteridge Road'],
    ZamorRuins: ['MountaintopsOfTheGiants', 76501, 'Zamor Ruins'],
  },
  'Flame Peak': {
    ChurchofRepose: ['FlamePeak', 76507, 'Church of Repose'],
    FireGiant: ['FlamePeak', 76509, 'Fire Giant'],
    FootoftheForge: ['FlamePeak', 76508, 'Foot of the Forge'],
    ForgeoftheGiants: ['FlamePeak', 76510, 'Forge of the Giants'],
    GiantConqueringHerosGrave: [
      'FlamePeak',
      73017,
      "Giant-Conquering Hero's Grave",
    ],
    GiantsGravepost: ['FlamePeak', 76506, "Giant's Gravepost"],
    GiantsMountaintopCatacombs: [
      'FlamePeak',
      73018,
      "Giant's Mountaintop Catacombs",
    ],
  },
  'Consecrated Snowfield': {
    ApostateDerelict: ['ConsecratedSnowfield', 76653, 'Apostate Derelict'],
    CaveoftheForlorn: ['ConsecratedSnowfield', 73112, 'Cave of the Forlorn'],
    ConsecratedSnowfield: [
      'ConsecratedSnowfield',
      76550,
      'Consecrated Snowfield',
    ],
    ConsecratedSnowfieldCatacombs: [
      'ConsecratedSnowfield',
      73019,
      'Consecrated Snowfield Catacombs',
    ],
    InnerConsecratedSnowfield: [
      'ConsecratedSnowfield',
      76551,
      'Inner Consecrated Snowfield',
    ],
    OrdinaLiturgicalTown: [
      'ConsecratedSnowfield',
      76652,
      'Ordina, Liturgical Town',
    ],
    YeloughAnixTunnel: ['ConsecratedSnowfield', 73211, 'Yelough Anix Tunnel'],
  },
  "Miquella's Haligtree": {
    HaligtreeCanopy: ['MiquellasHaligtree', 71506, 'Haligtree Canopy'],
    HaligtreePromenade: ['MiquellasHaligtree', 71505, 'Haligtree Promenade'],
    HaligtreeTown: ['MiquellasHaligtree', 71507, 'Haligtree Town'],
    HaligtreeTownPlaza: ['MiquellasHaligtree', 71508, 'Haligtree Town Plaza'],
  },
  'Elphael, Brace of the Haligtree': {
    DrainageChannel: ['ElphaelBraceOfTheHaligtree', 71503, 'Drainage Channel'],
    ElphaelInnerWall: [
      'ElphaelBraceOfTheHaligtree',
      71502,
      'Elphael Inner Wall',
    ],
    HaligtreeRoots: ['ElphaelBraceOfTheHaligtree', 71504, 'Haligtree Roots'],
    MaleniaGodessofRot: [
      'ElphaelBraceOfTheHaligtree',
      71500,
      'Malenia, Godess of Rot',
    ],
    PrayerRoom: ['ElphaelBraceOfTheHaligtree', 71501, 'Prayer Room'],
  },
  'Crumbling Farum Azula': {
    BesidethegreatBridge: [
      'CrumblingFarumAzula',
      71310,
      'Beside the great Bridge',
    ],
    CrumblingBeastGrave: [
      'CrumblingFarumAzula',
      71303,
      'Crumbling Beast Grave',
    ],
    CrumblingBeastGraveDepths: [
      'CrumblingFarumAzula',
      71304,
      'Crumbling Beast Grave Depths',
    ],
    DragonlordPlacidusax: [
      'CrumblingFarumAzula',
      71301,
      'Dragonlord Placidusax',
    ],
    DragonTemple: ['CrumblingFarumAzula', 71306, 'Dragon Temple'],
    DragonTempleAltar: ['CrumblingFarumAzula', 71302, 'Dragon Temple Altar'],
    DragonTempleLift: ['CrumblingFarumAzula', 71308, 'Dragon Temple Lift'],
    DragonTempleRooftop: [
      'CrumblingFarumAzula',
      71309,
      'Dragon Temple Rooftop',
    ],
    DragonTempleTransept: [
      'CrumblingFarumAzula',
      71307,
      'Dragon Temple Transept',
    ],
    MalikeththeBlackBlade: [
      'CrumblingFarumAzula',
      71300,
      'Maliketh, the Black Blade',
    ],
    TempestFacingBalcony: [
      'CrumblingFarumAzula',
      71305,
      'Tempest-Facing Balcony',
    ],
  },
  'Ainsel River': {
    AinselRiverDownstream: ['AinselRiver', 71213, 'Ainsel River Downstream'],
    AinselRiverSluiceGate: ['AinselRiver', 71212, 'Ainsel River Sluice Gate'],
    AinselRiverWellDepths: ['AinselRiver', 71211, 'Ainsel River Well Depths'],
    AstelNaturalbornoftheVoid: [
      'AinselRiver',
      71240,
      'Astel, Naturalborn of the Void',
    ],
    DragonkinSoldierofNokstella: [
      'AinselRiver',
      71210,
      'Dragonkin Soldier of Nokstella',
    ],
  },
  'Ainsel River Main': {
    AinselRiverMain: ['AinselRiverMain', 71214, 'Ainsel River Main'],
    NokstellaEternalCity: ['AinselRiverMain', 71215, 'Nokstella, Eternal City'],
    NokstellaWaterfallBasin: [
      'AinselRiverMain',
      71219,
      'Nokstella Waterfall Basin',
    ],
  },
  'Lake Of Rot': {
    GrandCloister: ['LakeOfRot', 71218, 'Grand Cloister'],
    LakeofRotShoreside: ['LakeOfRot', 71216, 'Lake of Rot Shoreside'],
  },
  'Nokron, Eternal City': {
    AncestralWoods: ['NokronEternalCity', 71224, 'Ancestral Woods'],
    AqueductFacingCliffs: [
      'NokronEternalCity',
      71225,
      'Aqueduct-Facing Cliffs',
    ],
    GreatWaterfallBasin: ['NokronEternalCity', 71220, 'Great Waterfall Basin'],
    MimicTear: ['NokronEternalCity', 71221, 'Mimic Tear'],
    NightsSacredGround: ['NokronEternalCity', 71226, "Night's Sacred Ground"],
    NokronEternalCity: ['NokronEternalCity', 71271, 'Nokron, Eternal City'],
  },
  'Siofra River': {
    BelowtheWell: ['SiofraRiver', 71227, 'Below the Well'],
    SiofraRiverBank: ['SiofraRiver', 71222, 'Siofra River Bank'],
    SiofraRiverWellDepths: ['SiofraRiver', 71270, 'Siofra River Well Depths'],
    WorshippersWoods: ['SiofraRiver', 71223, "Worshippers' Woods"],
  },
  'Mohgwyn Palace': {
    CocoonoftheEmpyrean: ['MohgwynPalace', 71250, 'Cocoon of the Empyrean'],
    DynastyMausoleumEntrance: [
      'MohgwynPalace',
      71252,
      'Dynasty Mausoleum Entrance',
    ],
    DynastyMausoleumMidpoint: [
      'MohgwynPalace',
      71253,
      'Dynasty Mausoleum Midpoint',
    ],
    PalaceApproachLedgeRoad: [
      'MohgwynPalace',
      71251,
      'Palace Approach Ledge-Road',
    ],
  },
  'Deeproot Depths': {
    AcrosstheRoots: ['DeeprootDepths', 71235, 'Across the Roots'],
    DeeprootDepths: ['DeeprootDepths', 71233, 'Deeproot Depths'],
    GreatWaterfallCrest: ['DeeprootDepths', 71232, 'Great Waterfall Crest'],
    PrinceofDeathsThrone: ['DeeprootDepths', 71230, "Prince of Death's Throne"],
    RootFacingCliffs: ['DeeprootDepths', 71231, 'Root-Facing Cliffs'],
    TheNamelessEternalCity: [
      'DeeprootDepths',
      71234,
      'The Nameless Eternal City',
    ],
  },
};
