/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppQuestsRouteImport } from './routes/_app/quests'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppCreditsRouteImport } from './routes/_app/credits'
import { Route as AppBuildRouteImport } from './routes/_app/build'
import { Route as AppBossesRouteImport } from './routes/_app/bosses'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsRoute = AppQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildRoute = AppBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AppRoute,
} as any)
const AppBossesRoute = AppBossesRouteImport.update({
  id: '/bosses',
  path: '/bosses',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/share': typeof ShareRoute
  '/bosses': typeof AppBossesRoute
  '/build': typeof AppBuildRoute
  '/credits': typeof AppCreditsRoute
  '/inventory': typeof AppInventoryRoute
  '/overview': typeof AppOverviewRoute
  '/quests': typeof AppQuestsRoute
}
export interface FileRoutesByTo {
  '/share': typeof ShareRoute
  '/bosses': typeof AppBossesRoute
  '/build': typeof AppBuildRoute
  '/credits': typeof AppCreditsRoute
  '/inventory': typeof AppInventoryRoute
  '/overview': typeof AppOverviewRoute
  '/quests': typeof AppQuestsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/share': typeof ShareRoute
  '/_app/bosses': typeof AppBossesRoute
  '/_app/build': typeof AppBuildRoute
  '/_app/credits': typeof AppCreditsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/quests': typeof AppQuestsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/share'
    | '/bosses'
    | '/build'
    | '/credits'
    | '/inventory'
    | '/overview'
    | '/quests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/share'
    | '/bosses'
    | '/build'
    | '/credits'
    | '/inventory'
    | '/overview'
    | '/quests'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/share'
    | '/_app/bosses'
    | '/_app/build'
    | '/_app/credits'
    | '/_app/inventory'
    | '/_app/overview'
    | '/_app/quests'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ShareRoute: typeof ShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quests': {
      id: '/_app/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AppQuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credits': {
      id: '/_app/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/build': {
      id: '/_app/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof AppBuildRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bosses': {
      id: '/_app/bosses'
      path: '/bosses'
      fullPath: '/bosses'
      preLoaderRoute: typeof AppBossesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBossesRoute: typeof AppBossesRoute
  AppBuildRoute: typeof AppBuildRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppQuestsRoute: typeof AppQuestsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBossesRoute: AppBossesRoute,
  AppBuildRoute: AppBuildRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppQuestsRoute: AppQuestsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ShareRoute: ShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
