// Per-item icon URLs, owned by this package and resolved by the consuming bundler.
//
// The 2939 icons live in `images/icons/items/{iconId}.webp` (extractor output, Git LFS).
// Rather than copy them into the web app's `public/`, we let the bundler (Vite) hash and
// emit them as build assets: `import.meta.glob` over our own asset dir returns a map of
// path → resolved URL. Because this package is consumed as *source* (`exports` points at
// `./src/*.ts`), the glob is transformed in the consumer's module graph.
//
/// <reference types="vite/client" />

// Only Vite-based consumers (the web app, via `@elden-ring-compass/data/images`) import
// this module — the data barrel (`.`) does not, so node/test consumers never hit the glob.
//
// `import.meta.glob` is a Vite compile-time macro: it is statically replaced during transform
// and MUST be called directly (aliasing it to a variable breaks the replacement). The
// `vite/client` reference above types the macro so both this package's typecheck and the
// web app's see it identically.
const itemIconModules = import.meta.glob<string>(
  '../images/icons/items/*.webp',
  {
    query: '?url',
    import: 'default',
    eager: true,
  },
);

// Small (80px) thumbnails of the same icons. The full icons are 100–160KB each
// (full-res), which is wasteful for the ~40px thumbnail shown in data-table rows —
// a virtualized table downloads one per visible row and saturates the connection.
// The thumbnails are ~2–4KB; use them for table cells and reserve the full image
// for the hover tooltip (one request, on demand). Generated by
// `packages/extractor/scripts/gen-icon-thumbs.ts` and by the extractor itself.
const itemIconThumbModules = import.meta.glob<string>(
  '../images/icons/items-thumb/*.webp',
  {
    query: '?url',
    import: 'default',
    eager: true,
  },
);

const urlMapByIconId = (
  modules: Record<string, string>,
): ReadonlyMap<number, string> =>
  new Map(
    Object.entries(modules).flatMap(([path, url]) => {
      const file = path.slice(path.lastIndexOf('/') + 1);
      const id = Number.parseInt(file, 10);
      return Number.isNaN(id) ? [] : [[id, url] as const];
    }),
  );

/** `{iconId}.webp` → hashed asset URL, keyed by the numeric icon id. */
export const ITEM_ICON_URL: ReadonlyMap<number, string> =
  urlMapByIconId(itemIconModules);

/** `{iconId}.webp` → hashed thumbnail URL (80px), keyed by the numeric icon id. */
export const ITEM_ICON_THUMB_URL: ReadonlyMap<number, string> =
  urlMapByIconId(itemIconThumbModules);

/** Resolve an item `icon` id to its bundled URL, or `undefined` if no icon exists. */
export function itemIconUrl(iconId: number): string | undefined {
  return ITEM_ICON_URL.get(iconId);
}

/**
 * Resolve an item `icon` id to its small (80px) thumbnail URL. Falls back to the
 * full-size URL if a thumbnail hasn't been generated for this id.
 */
export function itemIconThumbUrl(iconId: number): string | undefined {
  return ITEM_ICON_THUMB_URL.get(iconId) ?? ITEM_ICON_URL.get(iconId);
}
