/**
 * Parity test for the pure-TS parser on the committed `ER0000.sl2` fixture (5 active slots),
 * against two independent goldens:
 *
 *  1. `oracle.er0000.json` — the FROZEN golden captured from the (now-retired) verified
 *     Rust/WASM parser. It only covers the ORIGINAL lean fields, so we compare a deep SUBSET
 *     of each parsed slot (restricted to the oracle's keys) — this keeps the original fields,
 *     incl. the SHA-256-pinned event-flag bitfield, byte-for-byte. (M1 made the parser
 *     Effect-native without changing these; M2 added fields, which the subset ignores.)
 *
 *  2. `reference-fields.er0000.json` — the M2 golden for the NEWLY-extracted fields (HP/FP/
 *     stamina, buildups, flasks, online/cosmetic flags, equipped spells/gestures, active
 *     weapon slots, physick, projectiles, horse/bloodstain, world time/weather, deaths,
 *     playtime, DLC, …). It is generated by the er-save-manager Python reference parser
 *     (an independent implementation) via `fixtures/gen-reference-fields.py` — re-run that
 *     script (see its header for the `uv` command) to regenerate it.
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { Effect } from 'effect';
import { describe, expect, it } from 'vitest';

import { parseSave } from '../src/index.ts';

const here = (rel: string) => fileURLToPath(new URL(rel, import.meta.url));

const fixture = readFileSync(here('./fixtures/ER0000.sl2'));
const arrayBuffer = fixture.buffer.slice(
  fixture.byteOffset,
  fixture.byteOffset + fixture.byteLength,
);

type OracleSlot = Record<string, unknown> & {
  event_flags: { flags_length: number; flags_sha256: string };
};
const oracle = JSON.parse(
  readFileSync(here('./fixtures/oracle.er0000.json'), 'utf8'),
) as {
  global_steam_id: string;
  character_steam_ids: string[];
  slots: OracleSlot[];
};

const reference = JSON.parse(
  readFileSync(here('./fixtures/reference-fields.er0000.json'), 'utf8'),
) as { global_steam_id: string; slots: Record<string, unknown>[] };

const parsed = Effect.runSync(parseSave(arrayBuffer));

const sha256 = (b: Uint8Array) => createHash('sha256').update(b).digest('hex');

/** Replace the parser's Uint8Array flags with the oracle's {length, sha256} form. */
const normalize = (slot: (typeof parsed.slots)[number]) => ({
  ...slot,
  event_flags: {
    flags_length: slot.event_flags.flags.length,
    flags_sha256: sha256(slot.event_flags.flags),
  },
});

/**
 * Recursively keep only the keys present in `template` (the oracle slot), so M2's added
 * fields are ignored while the original fields stay strictly pinned. Arrays are compared
 * whole (the oracle's array elements never gained keys).
 */
const deepPick = (value: unknown, template: unknown): unknown => {
  if (Array.isArray(template)) return value;
  if (template && typeof template === 'object') {
    const v = value as Record<string, unknown>;
    return Object.fromEntries(
      Object.keys(template).map((k) => [
        k,
        deepPick(v[k], (template as Record<string, unknown>)[k]),
      ]),
    );
  }
  return value;
};

/** Project a parsed slot into the shape of the Python reference's NEW-field golden. */
const projectNewFields = (s: (typeof parsed.slots)[number]) => {
  const p = s.player_game_data;
  return {
    version: s.version,
    steam_id: s.steam_id,
    seconds_played: s.seconds_played,
    character_name: p.character_name,
    level: p.level,
    hp: p.hp,
    max_hp: p.max_hp,
    base_max_hp: p.base_max_hp,
    fp: p.fp,
    max_fp: p.max_fp,
    base_max_fp: p.base_max_fp,
    stamina: p.stamina,
    max_stamina: p.max_stamina,
    base_max_stamina: p.base_max_stamina,
    buildup: p.buildup,
    voice_type: p.voice_type,
    gift: p.gift,
    additional_talisman_slot_count: p.additional_talisman_slot_count,
    summon_spirit_level: p.summon_spirit_level,
    furl: p.furl_calling_finger_on,
    white_cipher: p.white_cipher_ring_on,
    blue_cipher: p.blue_cipher_ring_on,
    great_rune: p.great_rune_on,
    max_crimson: p.max_crimson_flask_count,
    max_cerulean: p.max_cerulean_flask_count,
    active_weapon_slots: s.active_weapon_slots,
    equipped_spells: s.equipped_spells,
    equipped_gestures: s.equipped_gestures,
    gestures_nonzero: s.gestures.filter((g) => g !== 0 && g !== 0xfffffffe)
      .length,
    gestures_len: s.gestures.length,
    equipped_physics: s.equipped_physics,
    acquired_projectiles: s.acquired_projectiles,
    horse: s.horse,
    blood_stain: s.blood_stain,
    world_time: s.world_time,
    world_weather: s.world_weather,
    base_version: s.base_version,
    deaths: s.deaths,
    last_rested_grace: s.last_rested_grace,
    spawn_point_entity_id: s.spawn_point_entity_id,
    dlc: s.dlc,
    map_id: s.map_id,
  };
};

describe('TS save parser parity (ER0000.sl2)', () => {
  it('matches account-level fields', () => {
    expect(parsed.global_steam_id).toBe(oracle.global_steam_id);
    expect(parsed.character_steam_ids).toEqual(oracle.character_steam_ids);
    expect(parsed.slots).toHaveLength(oracle.slots.length);
    expect(parsed.slots).toHaveLength(reference.slots.length);
  });

  for (let i = 0; i < oracle.slots.length; i++) {
    it(`slot[${i}] original fields match the WASM oracle byte-for-byte`, () => {
      const parsedSlot = parsed.slots[i];
      if (parsedSlot === undefined) throw new Error(`missing parsed slot ${i}`);
      const slot = normalize(parsedSlot);
      expect(deepPick(slot, oracle.slots[i])).toEqual(oracle.slots[i]);
    });

    it(`slot[${i}] new fields match the Python reference`, () => {
      const parsedSlot = parsed.slots[i];
      if (parsedSlot === undefined) throw new Error(`missing parsed slot ${i}`);
      expect(projectNewFields(parsedSlot)).toEqual(reference.slots[i]);
    });
  }
});
