import { Effect, FileSystem, Path } from 'effect';

import type { Archetype } from '../game/archetypes.ts';
import type { BossArea } from '../game/bosses.ts';
import { loadEventFlagBst } from '../game/event-flags.ts';
import type { Grace } from '../game/graces.ts';
import type { ItemText } from '../game/item-text.ts';
import type { MapFragment } from '../game/map-fragments.ts';
import type { Region } from '../game/regions.ts';
import type { ClassifiedMarker } from '../game/marker-classify.ts';
import type { Placement } from '../game/placements.ts';
import type { SpEffectLabel } from '../game/sp-effect-labels.ts';
import type { LegacyConv } from '../game/world-map-legacy-conv.ts';
import type {
  ArmorRecord,
  AshOfWarRecord,
  AttackElementCorrectRecord,
  CalcCorrectGraphRecord,
  GoodRecord,
  ReinforceTypeRecord,
  SpellRecord,
  SpiritAshRecord,
  TalismanRecord,
  WeaponRecord,
  WeaponScalingRecord,
} from './join.ts';

/**
 * Stage 9 — codegen. Writes the extracted datasets as typed `.ts` files into the
 * `@elden-ring-compass/data` workspace package (`packages/data/src/
 * generated/`) — the single source of truth the web app depends on. Output is
 * deterministic (stable sort, fixed field order) so re-running on an unchanged
 * install produces an identical diff-free tree. The legacy hand/erdb files under
 * apps/web stay until the app is migrated to consume this package.
 */

export interface CodegenInput {
  readonly graces: readonly Grace[];
  readonly bosses: readonly BossArea[];
  readonly regions: readonly Region[];
  readonly matchmakingRegionIds: readonly number[];
  readonly mapFragments: readonly MapFragment[];
  readonly archetypes: readonly Archetype[];
  readonly weapons: readonly WeaponRecord[];
  readonly armor: readonly ArmorRecord[];
  readonly talismans: readonly TalismanRecord[];
  readonly goods: readonly GoodRecord[];
  readonly ashesOfWar: readonly AshOfWarRecord[];
  readonly spells: readonly SpellRecord[];
  readonly spiritAshes: readonly SpiritAshRecord[];
  readonly weaponScaling: readonly WeaponScalingRecord[];
  readonly reinforceTypes: readonly ReinforceTypeRecord[];
  readonly attackElementCorrects: readonly AttackElementCorrectRecord[];
  readonly calcCorrectGraphs: readonly CalcCorrectGraphRecord[];
  readonly markers: readonly ClassifiedMarker[];
  readonly placements: readonly Placement[];
  readonly legacyConv: readonly LegacyConv[];
  readonly spEffects: readonly SpEffectLabel[];
  // Name tables for the remaining categories without a decoded stat record
  // (weapon arts) — emitted as {id, name}.
  readonly names: ItemText;
  // Elden Ring version this dataset was extracted from (e.g. "1.16.0.0"), or
  // null if it couldn't be read. Surfaced in the web UI.
  readonly gameVersion: string | null;
}

interface NamedRecord {
  readonly id: number;
  readonly name: string;
}

/** Sorted {id, name} rows from a name FMG map, dropping blank/[ERROR] entries. */
const nameRows = (table: ReadonlyMap<number, string>): NamedRecord[] =>
  [...table.entries()]
    .filter(([, n]) => n.trim().length > 0 && n !== '[ERROR]')
    .map(([id, name]) => ({ id, name }))
    .toSorted((a, b) => a.id - b.id);

// The generated package lives next to the extractor in the monorepo; resolve it
// from this module so the output dir is independent of the process cwd.
const GENERATED_DIR = new URL('../../../data/src/generated/', import.meta.url);

const HEADER =
  '// @generated by @elden-ring-compass/extractor — do not edit by hand.\n' +
  '// Regenerate with `bun run extract` against an Elden Ring install.\n\n';

/** Render `export interface <type> { … }` + `export const <name>: readonly <type>[]`. */
const renderDataset = (
  typeName: string,
  fields: readonly string[],
  constName: string,
  rows: readonly object[],
): string => {
  const iface = `export interface ${typeName} {\n${fields.map((f) => `  ${f}`).join('\n')}\n}\n\n`;
  const body = rows.map((r) => `  ${JSON.stringify(r)},`).join('\n');
  return `${HEADER}${iface}export const ${constName}: readonly ${typeName}[] = [\n${body}\n];\n`;
};

/**
 * Like `renderDataset`, but emits the rows via a single `JSON.parse(...)` literal
 * instead of an inline array. For very large datasets the inline-array form makes
 * TypeScript infer a giant element union and bail with TS2590 ("union type too
 * complex"); a JSON string is `any` at parse time, so it sidesteps that (and
 * type-checks + parses faster). Runtime cost is one parse at module load.
 */
const renderDatasetJson = (
  typeName: string,
  fields: readonly string[],
  constName: string,
  rows: readonly object[],
): string => {
  const iface = `export interface ${typeName} {\n${fields.map((f) => `  ${f}`).join('\n')}\n}\n\n`;
  const json = JSON.stringify(JSON.stringify(rows));
  return `${HEADER}${iface}export const ${constName}: readonly ${typeName}[] =\n  JSON.parse(${json}) as readonly ${typeName}[];\n`;
};

const write = (fileName: string, contents: string) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const filePath = yield* path.fromFileUrl(new URL(fileName, GENERATED_DIR));
    yield* fs.writeFileString(filePath, contents);
  });

/** Emit the event-flag addressing table + `eventFlagOffset()` reader (hand-shaped code). */
const renderEventFlags = (
  bst: ReadonlyArray<readonly [number, number]>,
): string =>
  `${HEADER}// Event-flag block → byte-offset multiplier (vendored ER-Save-Lib eventflag_bst).\n` +
  `export const EVENT_FLAG_BST: ReadonlyMap<number, number> = new Map([\n` +
  `${bst.map(([b, m]) => `  [${b}, ${m}],`).join('\n')}\n]);\n\n` +
  `/**\n` +
  ` * Resolve an event-flag id to its [byteOffset, bitPos] in the save's event-flag\n` +
  ` * bitfield. Returns null for an unknown block. (ER-Save-Lib formula.)\n` +
  ` */\n` +
  `export function eventFlagOffset(\n  id: number,\n): readonly [number, number] | null {\n` +
  `  const mult = EVENT_FLAG_BST.get(Math.floor(id / 1000));\n` +
  `  if (mult === undefined) return null;\n` +
  `  const index = id % 1000;\n` +
  `  return [mult * 125 + Math.floor(index / 8), 7 - (index % 8)];\n` +
  `}\n`;

/**
 * Render `generated/regions.ts` — the `REGIONS` table plus the `MATCHMAKING_REGION_IDS`
 * ignore-set. Self-contained (sorts its own inputs) so it can be regenerated in isolation.
 */
export const renderRegionsFile = (
  regionsInput: readonly Region[],
  matchmakingRegionIdsInput: readonly number[],
): string => {
  const regions = [...regionsInput].toSorted((a, b) => a.id - b.id);
  const matchmakingIds = [...matchmakingRegionIdsInput].toSorted(
    (a, b) => a - b,
  );
  // Pack the matchmaking ids 12-per-line so the Set stays readable in diffs.
  const matchmakingLines: string[] = [];
  for (let i = 0; i < matchmakingIds.length; i += 12) {
    matchmakingLines.push(
      '  ' + matchmakingIds.slice(i, i + 12).join(', ') + ',',
    );
  }
  return (
    renderDataset(
      'Region',
      [
        'readonly id: number;',
        'readonly name: string;',
        'readonly area: string | null;',
        'readonly isOpenWorld: boolean;',
        'readonly isDungeon: boolean;',
      ],
      'REGIONS',
      regions.map((r) => ({ ...r })),
    ) +
    '\n// areaNo==0 PlayRegionParam rowIds — multiplayer/invasion matchmaking siblings of placed\n' +
    "// regions. The game activates these as the player moves, so they appear in the save's\n" +
    '// unlocked_regions, but they have no name/placement and are NOT user-facing places.\n' +
    'export const MATCHMAKING_REGION_IDS: ReadonlySet<number> = new Set([\n' +
    `${matchmakingLines.join('\n')}\n]);\n`
  );
};

/** Render `generated/markers.ts` — classified MSB entities. Self-contained (sorts its inputs). */
export const renderMarkersFile = (
  markersInput: readonly ClassifiedMarker[],
): string => {
  const markers = [...markersInput].toSorted(
    (a, b) => a.mapId.localeCompare(b.mapId) || a.entityID - b.entityID,
  );
  return renderDataset(
    'MapMarker',
    [
      'readonly mapId: string;',
      // kind is 'part' | 'region' but typed `string`: a literal union over
      // ~24k rows overflows the type checker (TS2590). Same for `category`.
      'readonly kind: string;',
      'readonly type: number;',
      'readonly category: string;',
      'readonly name: string;',
      'readonly displayName: string | null;',
      'readonly entityId: number;',
      'readonly x: number;',
      'readonly y: number;',
      'readonly z: number;',
      'readonly npcParamId: number | null;',
    ],
    'MAP_MARKERS',
    markers.map((m) => ({
      mapId: m.mapId,
      kind: m.kind,
      type: m.type,
      category: m.category,
      name: m.name,
      displayName: m.displayName,
      entityId: m.entityID,
      x: m.x,
      y: m.y,
      z: m.z,
      npcParamId: m.npcParamId,
    })),
  );
};

/** Render `generated/placements.ts` — item world-placements. Self-contained (sorts its inputs). */
export const renderPlacementsFile = (
  placementsInput: readonly Placement[],
): string => {
  const placements = [...placementsInput].toSorted(
    (a, b) =>
      a.mapId.localeCompare(b.mapId) ||
      a.source.localeCompare(b.source) ||
      a.lotId - b.lotId ||
      a.entityId - b.entityId ||
      a.itemId - b.itemId,
  );
  // JSON.parse form: PLACEMENTS is large enough that an inline array literal trips
  // TS2590 ("union type too complex"). See `renderDatasetJson`.
  return renderDatasetJson(
    'Placement',
    [
      'readonly mapId: string;',
      'readonly entityId: number;',
      'readonly x: number;',
      'readonly y: number;',
      'readonly z: number;',
      'readonly npcParamId: number | null;',
      'readonly lotId: number;',
      'readonly itemId: number;',
      'readonly itemType: string;',
      'readonly quantity: number;',
      'readonly chance: number;',
      'readonly source: string;',
    ],
    'PLACEMENTS',
    placements.map((p) => ({ ...p })),
  );
};

/**
 * Render `generated/world-map-legacy-conv.ts` — per-base-point dungeon→overworld
 * projection offsets (`WorldMapLegacyConvParam`). Self-contained (sorts its inputs).
 */
export const renderLegacyConvFile = (
  convInput: readonly LegacyConv[],
): string => {
  const rows = [...convInput].toSorted(
    (a, b) => a.srcMapId.localeCompare(b.srcMapId) || a.srcX - b.srcX,
  );
  return renderDataset(
    'LegacyConv',
    [
      'readonly srcMapId: string;',
      "readonly master: 'M00' | 'M01' | 'M10' | 'M11';",
      'readonly srcX: number;',
      'readonly srcZ: number;',
      'readonly addX: number;',
      'readonly addZ: number;',
    ],
    'WORLD_MAP_LEGACY_CONV',
    rows.map((c) => ({ ...c })),
  );
};

/**
 * Render `generated/sp-effects.ts` — `sp_effect_id → granting-item label`, for
 * naming a save's active `sp_effects[]`. Self-contained (sorts its inputs).
 * Coverage is PARTIAL by design (direct refs only; nested-leaf SpEffects are
 * unlabeled — see `game/sp-effect-labels.ts`).
 */
export const renderSpEffectsFile = (
  spEffectsInput: readonly SpEffectLabel[],
): string => {
  const rows = [...spEffectsInput].toSorted((a, b) => a.id - b.id);
  return renderDataset(
    'SpEffectLabel',
    [
      'readonly id: number;',
      'readonly label: string;',
      'readonly source: string;',
    ],
    'SP_EFFECT_LABELS',
    rows.map((r) => ({ ...r })),
  );
};

export const codegen = (input: CodegenInput) =>
  Effect.gen(function* () {
    // Sort each dataset by a stable key for deterministic, diff-friendly output.
    const graces = [...input.graces].toSorted((a, b) => a.flagId - b.flagId);
    const bosses = [...input.bosses].toSorted(
      (a, b) => a.defeatFlagId - b.defeatFlagId,
    );
    const weapons = [...input.weapons].toSorted((a, b) => a.id - b.id);

    yield* write(
      'graces.ts',
      renderDataset(
        'Grace',
        [
          'readonly flagId: number;',
          'readonly name: string;',
          'readonly region: string | null;',
          'readonly bonfireEntityId: number;',
          'readonly mapArea: number;',
        ],
        'GRACES',
        graces.map((g) => ({
          flagId: g.flagId,
          name: g.name,
          region: g.region,
          bonfireEntityId: g.bonfireEntityId,
          mapArea: g.areaNo,
        })),
      ),
    );

    yield* write(
      'bosses.ts',
      renderDataset(
        'Boss',
        [
          'readonly defeatFlagId: number;',
          'readonly name: string | null;',
          'readonly mapId: string;',
          'readonly x: number;',
          'readonly y: number;',
          'readonly z: number;',
          'readonly runes: number;',
        ],
        'BOSSES',
        bosses.map((b) => ({
          defeatFlagId: b.defeatFlagId,
          name: b.name,
          mapId: b.mapId,
          x: b.x,
          y: b.y,
          z: b.z,
          runes: b.runes,
        })),
      ),
    );

    yield* write(
      'weapons.ts',
      renderDataset(
        'Weapon',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly category: string;',
          'readonly allowAshOfWar: boolean;',
          'readonly isBuffable: boolean;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly attackPhysical: number;',
          'readonly reqStrength: number;',
          'readonly reqDexterity: number;',
          'readonly reqIntelligence: number;',
          'readonly reqFaith: number;',
          'readonly reqArcane: number;',
          'readonly upgradeMaterial: string;',
          'readonly upgradeCosts: readonly number[];',
          'readonly effects: readonly { readonly attribute: string; readonly value: number; readonly model: string; readonly type: string; readonly conditions?: readonly string[] }[];',
        ],
        'WEAPONS',
        weapons.map((w) => ({ ...w })),
      ),
    );

    const armor = [...input.armor].toSorted((a, b) => a.id - b.id);
    yield* write(
      'armor.ts',
      renderDataset(
        'Armor',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly category: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly negationPhysical: number;',
          'readonly negationStrike: number;',
          'readonly negationSlash: number;',
          'readonly negationPierce: number;',
          'readonly negationMagic: number;',
          'readonly negationFire: number;',
          'readonly negationLightning: number;',
          'readonly negationHoly: number;',
          'readonly resistPoison: number;',
          'readonly resistScarletRot: number;',
          'readonly resistBleed: number;',
          'readonly resistFrost: number;',
          'readonly resistSleep: number;',
          'readonly resistMadness: number;',
          'readonly resistDeath: number;',
          'readonly poise: number;',
          'readonly effects: readonly { readonly attribute: string; readonly value: number; readonly model: string; readonly type: string; readonly conditions?: readonly string[] }[];',
        ],
        'ARMOR',
        armor.map((a) => ({ ...a })),
      ),
    );

    const talismans = [...input.talismans].toSorted((a, b) => a.id - b.id);
    yield* write(
      'talismans.ts',
      renderDataset(
        'Talisman',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly conflicts: readonly string[];',
          'readonly effects: readonly { readonly attribute: string; readonly value: number; readonly model: string; readonly type: string; readonly conditions?: readonly string[] }[];',
        ],
        'TALISMANS',
        talismans.map((t) => ({ ...t })),
      ),
    );

    // Goods (consumables, materials, spells, spirit ashes, key items, …) — one
    // table tagged with a derived category from EquipParamGoods.goodsType.
    const goods = [...input.goods].toSorted((a, b) => a.id - b.id);
    yield* write(
      'goods.ts',
      renderDataset(
        'Good',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly category: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly maxHeld: number;',
        ],
        'GOODS',
        goods.map((g) => ({ ...g })),
      ),
    );

    const ashesOfWar = [...input.ashesOfWar].toSorted((a, b) => a.id - b.id);
    yield* write(
      'ashes-of-war.ts',
      renderDataset(
        'AshOfWar',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly armamentCategories: readonly string[];',
          'readonly defaultAffinity: string;',
          'readonly possibleAffinities: readonly string[];',
          'readonly skillId: number;',
        ],
        'ASHES_OF_WAR',
        ashesOfWar.map((a) => ({ ...a })),
      ),
    );

    const spells = [...input.spells].toSorted((a, b) => a.id - b.id);
    yield* write(
      'spells.ts',
      renderDataset(
        'Spell',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly category: string;',
          'readonly fpCost: number;',
          'readonly fpCostExtra: number;',
          'readonly spCost: number;',
          'readonly slotsUsed: number;',
          'readonly reqIntelligence: number;',
          'readonly reqFaith: number;',
          'readonly reqArcane: number;',
          'readonly isWeaponBuff: boolean;',
        ],
        'SPELLS',
        spells.map((s) => ({ ...s })),
      ),
    );

    const spiritAshes = [...input.spiritAshes].toSorted((a, b) => a.id - b.id);
    yield* write(
      'spirit-ashes.ts',
      renderDataset(
        'SpiritAsh',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly summonName: string;',
          'readonly fpCost: number;',
          'readonly hpCost: number;',
          'readonly upgradeMaterial: string;',
          'readonly upgradeCosts: readonly number[];',
        ],
        'SPIRIT_ASHES',
        spiritAshes.map((s) => ({ ...s })),
      ),
    );

    // AR scaling model — per-weapon refs + the three shared lookup tables. The
    // runtime AR formula that consumes these lives in `@elden-ring-compass/data`
    // (`ar.ts`). Sorted by id for deterministic output.
    const weaponScaling = [...input.weaponScaling].toSorted(
      (a, b) => a.id - b.id,
    );
    yield* write(
      'weapon-scaling.ts',
      // JSON.parse form: 3k+ rows of nested objects trip TS2590 as an inline
      // array literal (like PLACEMENTS). See `renderDatasetJson`.
      renderDatasetJson(
        'WeaponScaling',
        [
          'readonly id: number;',
          'readonly reinforceTypeId: number;',
          'readonly attackElementCorrectId: number;',
          'readonly requirements: { readonly str?: number; readonly dex?: number; readonly int?: number; readonly fai?: number; readonly arc?: number };',
          'readonly baseAttack: { readonly physical?: number; readonly magic?: number; readonly fire?: number; readonly lightning?: number; readonly holy?: number };',
          'readonly scaling: { readonly str?: number; readonly dex?: number; readonly int?: number; readonly fai?: number; readonly arc?: number };',
          'readonly calcCorrectIds: { readonly physical?: number; readonly magic?: number; readonly fire?: number; readonly lightning?: number; readonly holy?: number };',
        ],
        'WEAPON_SCALING',
        weaponScaling.map((w) => ({ ...w })),
      ),
    );

    const reinforceTypes = [...input.reinforceTypes].toSorted(
      (a, b) => a.id - b.id,
    );
    yield* write(
      'reinforce-types.ts',
      // Many reinforce types × 26 levels of tuple arrays — JSON.parse form to stay
      // under the TS2590 union-complexity ceiling.
      renderDatasetJson(
        'ReinforceType',
        [
          'readonly id: number;',
          'readonly levels: readonly { readonly attack: readonly number[]; readonly scaling: readonly number[] }[];',
        ],
        'REINFORCE_TYPES',
        reinforceTypes.map((r) => ({ ...r })),
      ),
    );

    const attackElementCorrects = [...input.attackElementCorrects].toSorted(
      (a, b) => a.id - b.id,
    );
    yield* write(
      'attack-element-correct.ts',
      renderDataset(
        'AttackElementCorrect',
        [
          'readonly id: number;',
          'readonly correct: { readonly [damageType: string]: { readonly [attr: string]: number | true } };',
        ],
        'ATTACK_ELEMENT_CORRECTS',
        attackElementCorrects.map((a) => ({ ...a })),
      ),
    );

    const calcCorrectGraphs = [...input.calcCorrectGraphs].toSorted(
      (a, b) => a.id - b.id,
    );
    yield* write(
      'calc-correct-graphs.ts',
      renderDataset(
        'CalcCorrectGraph',
        [
          'readonly id: number;',
          'readonly stages: readonly { readonly maxVal: number; readonly maxGrowVal: number; readonly adjPt: number }[];',
        ],
        'CALC_CORRECT_GRAPHS',
        calcCorrectGraphs.map((c) => ({ ...c })),
      ),
    );

    // Weapon arts have no decoded stat record yet; emit as {id, name} (base + DLC).
    const nameTables: readonly [
      string,
      string,
      string,
      ReadonlyMap<number, string>,
    ][] = [['arts.ts', 'WeaponArt', 'ARTS', input.names.ArtsName]];
    const nameFields = ['readonly id: number;', 'readonly name: string;'];
    for (const [file, typeName, constName, table] of nameTables) {
      yield* write(
        file,
        renderDataset(typeName, nameFields, constName, nameRows(table)),
      );
    }

    yield* write('markers.ts', renderMarkersFile(input.markers));

    yield* write('placements.ts', renderPlacementsFile(input.placements));

    yield* write(
      'world-map-legacy-conv.ts',
      renderLegacyConvFile(input.legacyConv),
    );

    yield* write('sp-effects.ts', renderSpEffectsFile(input.spEffects));

    yield* write(
      'regions.ts',
      renderRegionsFile(input.regions, input.matchmakingRegionIds),
    );

    const mapFragments = [...input.mapFragments].toSorted(
      (a, b) => a.openEventFlagId - b.openEventFlagId,
    );
    yield* write(
      'map-fragments.ts',
      renderDataset(
        'MapFragment',
        [
          'readonly pieceId: number;',
          'readonly openEventFlagId: number;',
          'readonly acquisitionEventFlagId: number;',
          'readonly name: string | null;',
          'readonly areaNo: number;',
          'readonly gridX: number;',
          'readonly gridZ: number;',
        ],
        'MAP_FRAGMENTS',
        mapFragments.map((m) => ({ ...m })),
      ),
    );

    const archetypes = [...input.archetypes].toSorted((a, b) => a.id - b.id);
    yield* write(
      'archetypes.ts',
      renderDataset(
        'Archetype',
        ['readonly id: number;', 'readonly name: string;'],
        'ARCHETYPES',
        archetypes.map((a) => ({ ...a })),
      ),
    );

    yield* write('event-flags.ts', renderEventFlags(yield* loadEventFlagBst));

    // Dataset provenance — the game version it was extracted from. The version is
    // digits-and-dots (or null), so it's safe to quote directly.
    const versionLiteral =
      input.gameVersion === null ? 'null' : `'${input.gameVersion}'`;
    yield* write(
      'game-meta.ts',
      `${HEADER}/** Elden Ring version this dataset was extracted from (PE FileVersion of\n` +
        ` * eldenring.exe), or null if it couldn't be read. */\n` +
        `export const GAME_VERSION: string | null = ${versionLiteral};\n`,
    );

    const modules = [
      'graces',
      'bosses',
      'weapons',
      'armor',
      'talismans',
      'ashes-of-war',
      'goods',
      'spells',
      'spirit-ashes',
      'weapon-scaling',
      'reinforce-types',
      'attack-element-correct',
      'calc-correct-graphs',
      'arts',
      'regions',
      'map-fragments',
      'archetypes',
      'markers',
      'placements',
      'world-map-legacy-conv',
      'sp-effects',
      'event-flags',
      'game-meta',
    ];
    const index =
      HEADER +
      modules.map((m) => `export * from './${m}.ts';`).join('\n') +
      '\n';
    yield* write('index.ts', index);

    yield* Effect.logInfo(
      `codegen → @elden-ring-compass/data: ${graces.length} graces, ${bosses.length} bosses, ` +
        `${weapons.length} weapons, ${armor.length} armor, ${talismans.length} talismans, ` +
        `${goods.length} goods, ${ashesOfWar.length} ashes of war, ${spells.length} spells, ` +
        `${spiritAshes.length} spirit ashes, ${weaponScaling.length} weapon-scaling ` +
        `(${reinforceTypes.length} reinforce / ${attackElementCorrects.length} elem-correct / ` +
        `${calcCorrectGraphs.length} calc-correct), ${mapFragments.length} map fragments, ` +
        `${input.markers.length} markers, ${input.placements.length} placements, ` +
        `${input.legacyConv.length} legacy-conv base points, ` +
        `${input.spEffects.length} sp-effect labels (+ arts name table)`,
    );
  });
