export const COOKBOOKS = {
  "Missionary's Cookbook": {
    MissionarysCookbook1: [67610, "Missionary's Cookbook[1]"],
    MissionarysCookbook2: [67600, "Missionary's Cookbook[2]"],
    MissionarysCookbook3: [67650, "Missionary's Cookbook[3]"],
    MissionarysCookbook4: [67640, "Missionary's Cookbook[4]"],
    MissionarysCookbook5: [67630, "Missionary's Cookbook[5]"],
    MissionarysCookbook6: [67130, "Missionary's Cookbook[6]"],
    MissionarysCookbook7: [68230, "Missionary's Cookbook[7]"],
  },
  "Nomadic warrior's Cookbook": {
    NomadicwarriorsCookbook1: [67000, "Nomadic warrior's Cookbook[1]"],
    NomadicwarriorsCookbook2: [67110, "Nomadic warrior's Cookbook[2]"],
    NomadicwarriorsCookbook3: [67010, "Nomadic warrior's Cookbook[3]"],
    NomadicwarriorsCookbook4: [67800, "Nomadic warrior's Cookbook[4]"],
    NomadicwarriorsCookbook5: [67830, "Nomadic warrior's Cookbook[5]"],
    NomadicwarriorsCookbook6: [67020, "Nomadic warrior's Cookbook[6]"],
    NomadicwarriorsCookbook7: [67050, "Nomadic warrior's Cookbook[7]"],
    NomadicwarriorsCookbook8: [67880, "Nomadic warrior's Cookbook[8]"],
    NomadicwarriorsCookbook9: [67430, "Nomadic warrior's Cookbook[9]"],
    NomadicwarriorsCookbook10: [67030, "Nomadic warrior's Cookbook1[0]"],
    NomadicwarriorsCookbook11: [67220, "Nomadic warrior's Cookbook1[1]"],
    NomadicwarriorsCookbook12: [67060, "Nomadic warrior's Cookbook1[2]"],
    NomadicwarriorsCookbook13: [67080, "Nomadic warrior's Cookbook1[3]"],
    NomadicwarriorsCookbook14: [67870, "Nomadic warrior's Cookbook1[4]"],
    NomadicwarriorsCookbook15: [67900, "Nomadic warrior's Cookbook1[5]"],
    NomadicwarriorsCookbook16: [67290, "Nomadic warrior's Cookbook1[6]"],
    NomadicwarriorsCookbook17: [67100, "Nomadic warrior's Cookbook1[7]"],
    NomadicwarriorsCookbook18: [67270, "Nomadic warrior's Cookbook1[8]"],
    NomadicwarriorsCookbook19: [67070, "Nomadic warrior's Cookbook1[9]"],
    NomadicwarriorsCookbook20: [67230, "Nomadic warrior's Cookbook2[0]"],
    NomadicwarriorsCookbook21: [67120, "Nomadic warrior's Cookbook2[1]"],
    NomadicwarriorsCookbook22: [67890, "Nomadic warrior's Cookbook2[2]"],
    NomadicwarriorsCookbook23: [67090, "Nomadic warrior's Cookbook2[3]"],
    NomadicwarriorsCookbook24: [67910, "Nomadic warrior's Cookbook2[4]"],
  },
  "Armorer's Cookbook": {
    ArmorersCookbook1: [67200, "Armorer's Cookbook[1]"],
    ArmorersCookbook2: [67210, "Armorer's Cookbook[2]"],
    ArmorersCookbook3: [67280, "Armorer's Cookbook[3]"],
    ArmorersCookbook4: [67260, "Armorer's Cookbook[4]"],
    ArmorersCookbook5: [67310, "Armorer's Cookbook[5]"],
    ArmorersCookbook6: [67300, "Armorer's Cookbook[6]"],
    ArmorersCookbook7: [67250, "Armorer's Cookbook[7]"],
  },
  "Ancient Dragon Apostle's Cookbook": {
    AncientDragonApostlesCookbook1: [
      68000,
      "Ancient Dragon Apostle's Cookbook[1]",
    ],
    AncientDragonApostlesCookbook2: [
      68010,
      "Ancient Dragon Apostle's Cookbook[2]",
    ],
    AncientDragonApostlesCookbook3: [
      68030,
      "Ancient Dragon Apostle's Cookbook[3]",
    ],
    AncientDragonApostlesCookbook4: [
      68020,
      "Ancient Dragon Apostle's Cookbook[4]",
    ],
  },
  "Fevor's Cookbook": {
    FevorsCookbook1: [68200, 'Fevors Cookbook[1]'],
    FevorsCookbook2: [68220, 'Fevors Cookbook[2]'],
    FevorsCookbook3: [68210, 'Fevors Cookbook[3]'],
  },
  "Perfumer's Cookbook": {
    PerfumersCookbook1: [67840, "Perfumer's Cookbook[1]"],
    PerfumersCookbook2: [67850, "Perfumer's Cookbook[2]"],
    PerfumersCookbook3: [67860, "Perfumer's Cookbook[3]"],
    PerfumersCookbook4: [67920, "Perfumer's Cookbook[4]"],
  },
  "Glintstone Craftman's Cookbook": {
    GlintstoneCraftmansCookbook1: [67410, "Glintstone Craftman's Cookbook[1]"],
    GlintstoneCraftmansCookbook2: [67450, "Glintstone Craftman's Cookbook[2]"],
    GlintstoneCraftmansCookbook3: [67480, "Glintstone Craftman's Cookbook[3]"],
    GlintstoneCraftmansCookbook4: [67400, "Glintstone Craftman's Cookbook[4]"],
    GlintstoneCraftmansCookbook5: [67420, "Glintstone Craftman's Cookbook[5]"],
    GlintstoneCraftmansCookbook6: [67460, "Glintstone Craftman's Cookbook[6]"],
    GlintstoneCraftmansCookbook7: [67470, "Glintstone Craftman's Cookbook[7]"],
    GlintstoneCraftmansCookbook8: [67440, "Glintstone Craftman's Cookbook[8]"],
  },
  "Frenzied's Cookbook": {
    FrenziedsCookbook1: [68400, "Frenzied's Cookbook[1]"],
    FrenziedsCookbook2: [68410, "Frenzied's Cookbook[2]"],
  },
};
