export const MAP_NAMES = {
  RoundtableHold: 'Table of Lost Grace / Roundtable Hold',
  Limgrave: 'Limgrave',
  StrandedGraveyard: 'Stranded Graveyard',
  Stormhill: 'Stormhill',
  WeepingPeninsula: 'Weeping Peninsula',
  StormveilCastle: 'Stormveil Castle',
  LiurniaOfTheLakes: 'Liurnia of the Lakes',
  BellumHighway: 'Bellum Highway',
  RuinStrewnPrecipice: 'Ruin-Strewn Precipice',
  MoonlightAltar: 'Moonlight Altar',
  AcademyOfRayaLucaria: 'Academy of Raya Lucaria',
  AltusPlateau: 'Altus Plateau',
  MtGelmir: 'Mt. Gelmir',
  CapitalOutskirts: 'Capital Outskirts',
  VolcanoManor: 'Volcano Manor',
  LeyndellRoyalCapital: 'Leyndell, Royal Capital',
  SubterraneanShunningGrounds: 'Subterranean Shunning-Grounds',
  LeyndellAshenCapital: 'Leyndell, Ashen Capital',
  StonePlatform: 'Stone Platform',
  Caelid: 'Caelid',
  SwampOfAeonia: 'Swamp of Aeonia',
  GreyollsDragonbarrow: "Greyoll's Dragonbarrow",
  ForbiddenLands: 'Forbidden Lands',
  MountaintopsOfTheGiants: 'Mountaintops of the Giants',
  FlamePeak: 'Flame Peak',
  ConsecratedSnowfield: 'Consecrated Snowfield',
  MiquellasHaligtree: "Miquella's Haligtree",
  ElphaelBraceOfTheHaligtree: 'Elphael, Brace of the Haligtree',
  AinselRiver: 'Ainsel River',
  AinselRiverMain: 'Ainsel River Main',
  LakeOfRot: 'Lake of Rot',
  NokronEternalCity: 'Nokron, Eternal City',
  MohgwynPalace: 'Mohgwyn Palace',
  SiofraRiver: 'Siofra River',
  DeeprootDepths: 'Deeproot Depths',
  CrumblingFarumAzula: 'Crumbling Farum Azula',
};
