export const REGIONS = {
  ChurchofDragonCommunion: [
    6100090,
    'Church of Dragon Communion',
    'Limgrave',
    true,
    false,
    false,
  ],
  TheFirstStepChurchofElleh: [
    6100000,
    'The First Step, Church of Elleh',
    'Limgrave',
    true,
    false,
    false,
  ],
  SeasideRuins: [6100001, 'Seaside Ruins', 'Limgrave', true, false, false],
  MistwoodOutskirtsFortHaightWest: [
    6100004,
    'Mistwood Outskirts, Fort Haight West',
    'Limgrave',
    true,
    false,
    false,
  ],
  AgheelLakeNorthMurkwaterCoastGatefrontRuins: [
    6100002,
    'Agheel Lake North, Murkwater Coast, Gatefront Ruins',
    'Limgrave',
    true,
    false,
    false,
  ],
  SummonwaterVillageOutskirts: [
    6100003,
    'Summonwater Village Outskirts',
    'Limgrave',
    true,
    false,
    false,
  ],
  WaypointRuinsCellar: [
    6100010,
    'Waypoint Ruins Cellar',
    'Limgrave',
    true,
    false,
    false,
  ],
  StormfootCatacombs: [
    3002001,
    'Stormfoot Catacombs',
    'Limgrave',
    false,
    true,
    false,
  ],
  MurkwaterCatacombs: [
    3004001,
    'Murkwater Catacombs',
    'Limgrave',
    false,
    true,
    false,
  ],
  GrovesideCave: [3103001, 'Groveside Cave', 'Limgrave', false, true, false],
  CoastalCave: [3115001, 'Coastal Cave', 'Limgrave', false, true, false],
  MurkwaterCave: [3100001, 'Murkwater Cave', 'Limgrave', false, true, false],
  HighroadCave: [3117001, 'Highroad Cave', 'Limgrave', false, true, false],
  LimgraveTunnels: [
    3201001,
    'Limgrave Tunnels',
    'Limgrave',
    false,
    true,
    false,
  ],

  CaveofKnowledge: [
    1800090,
    'Cave of Knowledge',
    'StrandedGraveyard',
    false,
    true,
    false,
  ],
  StrandedGraveyard: [
    1800001,
    'Stranded Graveyard',
    'StrandedGraveyard',
    false,
    true,
    false,
  ],

  Stormhill: [6101000, 'Stormhill', 'Stormhill', true, false, false],
  MargittheFellOmen: [
    6101010,
    'Margit, the Fell Omen',
    'Stormhill',
    false,
    false,
    true,
  ],
  DeathtouchedCatacombs: [
    3011001,
    'Deathtouched Catacombs',
    'Stormhill',
    false,
    true,
    false,
  ],
  DivineTowerofLimgrave: [
    3410090,
    'Divine Tower of Limgrave',
    'Stormhill',
    false,
    false,
    false,
  ],

  CastleMorne: [
    6102001,
    'Castle Morne',
    'WeepingPeninsula',
    false,
    false,
    true,
  ],
  MorneMoangrave: [
    6102020,
    'Morne Moangrave',
    'WeepingPeninsula',
    false,
    false,
    true,
  ],
  WeepingPeninsulaEast: [
    6102000,
    'Weeping Peninsula East',
    'WeepingPeninsula',
    true,
    false,
    false,
  ],
  WeepingPeninsulaWest: [
    6102002,
    'Weeping Peninsula West',
    'WeepingPeninsula',
    true,
    false,
    false,
  ],
  ImpalersCatacombs: [
    3001001,
    "Impaler's Catacombs",
    'WeepingPeninsula',
    false,
    true,
    false,
  ],
  TombswardCatacombs: [
    3000001,
    'Tombsward Catacombs',
    'WeepingPeninsula',
    false,
    true,
    false,
  ],
  EarthboreCave: [
    3101001,
    'Earthbore Cave',
    'WeepingPeninsula',
    false,
    true,
    false,
  ],
  TombswardCave: [
    3102001,
    'Tombsward Cave',
    'WeepingPeninsula',
    false,
    true,
    false,
  ],
  MorneTunnel: [
    3200001,
    'Morne Tunnel',
    'WeepingPeninsula',
    false,
    true,
    false,
  ],

  StormveilMainGateStormveilCliffside: [
    1000001,
    'Stormveil Main Gate, Stormveil Cliffside',
    'StormveilCastle',
    false,
    false,
    false,
  ],
  GatesideChamber: [
    1000006,
    'Gateside Chamber',
    'StormveilCastle',
    false,
    false,
    false,
  ],
  RampartTower: [
    1000003,
    'Rampart Tower',
    'StormveilCastle',
    false,
    false,
    false,
  ],
  LiftsideChamberSecludedCell: [
    1000005,
    'Liftside Chamber, Secluded Cell',
    'StormveilCastle',
    false,
    false,
    true,
  ],
  GodricktheGrafted: [
    1000000,
    'Godrick the Grafted',
    'StormveilCastle',
    false,
    false,
    true,
  ],

  LiurniaSouthEast: [
    6200001,
    'Liurnia South-East',
    'LiurniaOfTheLakes',
    true,
    false,
    false,
  ],
  LiurniaEast: [
    6200004,
    'Liurnia East',
    'LiurniaOfTheLakes',
    true,
    false,
    false,
  ],
  BehindCariaManor: [
    6200008,
    'Behind Caria Manor',
    'LiurniaOfTheLakes',
    false,
    false,
    false,
  ],
  SlumberingWolfsShack: [
    3105090,
    "Slumbering Wolf's Shack",
    'LiurniaOfTheLakes',
    false,
    false,
    false,
  ],
  LiurniaSouth: [
    6200000,
    'Liurnia South',
    'LiurniaOfTheLakes',
    true,
    false,
    false,
  ],
  LiurniaSouthWest: [
    6200002,
    'Liurnia South-West',
    'LiurniaOfTheLakes',
    true,
    false,
    false,
  ],
  LiurniaWest: [
    6200005,
    'Liurnia West',
    'LiurniaOfTheLakes',
    true,
    false,
    false,
  ],
  KingsrealmRuins: [
    6200003,
    'Kingsrealm Ruins',
    'LiurniaOfTheLakes',
    true,
    false,
    false,
  ],
  MainCariaManorGate: [
    6200007,
    'Main Caria Manor Gate',
    'LiurniaOfTheLakes',
    true,
    false,
    false,
  ],
  CariaManor: [
    6200007,
    'Caria Manor',
    'LiurniaOfTheLakes',
    false,
    false,
    false,
  ],
  ManorLowerLevel: [
    6200007,
    'Manor Lower Level',
    'LiurniaOfTheLakes',
    false,
    false,
    false,
  ],
  RoyalMoongazingGrounds: [
    6200010,
    'Royal Moongazing Grounds',
    'LiurniaOfTheLakes',
    false,
    false,
    false,
  ],
  TheRavine: [6200006, 'The Ravine', 'LiurniaOfTheLakes', true, false, false],
  CliffbottomCatacombs: [
    3006001,
    'Cliffbottom Catacombs',
    'LiurniaOfTheLakes',
    false,
    true,
    false,
  ],
  RoadsEndCatacombs: [
    3003001,
    "Road's End Catacombs",
    'LiurniaOfTheLakes',
    false,
    true,
    false,
  ],
  BlackKnifeCatacombs: [
    3005001,
    'Black Knife Catacombs',
    'LiurniaOfTheLakes',
    false,
    true,
    false,
  ],
  StillwaterCave: [
    3104001,
    'Stillwater Cave',
    'LiurniaOfTheLakes',
    false,
    true,
    false,
  ],
  LakesideCrystalCave: [
    3105001,
    'Lakeside Crystal Cave',
    'LiurniaOfTheLakes',
    false,
    true,
    false,
  ],
  AcademyCrystalCave: [
    3106001,
    'Academy Crystal Cave',
    'LiurniaOfTheLakes',
    false,
    true,
    false,
  ],
  MainAcademyGate: [
    1400011,
    'Main Academy Gate',
    'LiurniaOfTheLakes',
    false,
    false,
    false,
  ],
  RayaLucariaCrystalTunnel: [
    3202001,
    'Raya Lucaria Crystal Tunnel',
    'LiurniaOfTheLakes',
    false,
    true,
    false,
  ],
  DivineTowerofLiurnia: [
    3411090,
    'Divine Tower of Liurnia',
    'LiurniaOfTheLakes',
    false,
    false,
    false,
  ],

  BellumHighway: [
    6201000,
    'Bellum Highway',
    'BellumHighway',
    true,
    false,
    false,
  ],
  GrandLiftofDectusJarburg: [
    6200090,
    'Grand Lift of Dectus, Jarburg',
    'BellumHighway',
    true,
    false,
    false,
  ],

  RuinStrewnPrecipice: [
    3920002,
    'Ruin-Strewn Precipice',
    'RuinStrewnPrecipice',
    false,
    false,
    false,
  ],
  RuinStrewnPrecipiceOverlook: [
    3920003,
    'Ruin-Strewn Precipice Overlook',
    'RuinStrewnPrecipice',
    false,
    false,
    true,
  ],
  MagmaWyrmMakar: [
    3920000,
    'Magma Wyrm Makar',
    'RuinStrewnPrecipice',
    false,
    false,
    true,
  ],

  MoonlightAltar: [
    6202000,
    'Moonlight Altar',
    'MoonlightAltar',
    false,
    false,
    false,
  ],

  ChurchoftheCuckoo: [
    1400013,
    'Church of the Cuckoo',
    'AcademyOfRayaLucaria',
    false,
    false,
    false,
  ],
  SchoolhouseClassroom: [
    1400015,
    'Schoolhouse Classroom',
    'AcademyOfRayaLucaria',
    false,
    false,
    false,
  ],
  DebateParlor: [
    1400010,
    'Debate Parlor',
    'AcademyOfRayaLucaria',
    false,
    false,
    false,
  ],
  RayaLucariaGrandLibrary: [
    1400000,
    'Raya Lucaria Grand Library',
    'AcademyOfRayaLucaria',
    false,
    false,
    true,
  ],

  RampartsidePath: [
    6300005,
    'Rampartside Path',
    'AltusPlateau',
    true,
    false,
    false,
  ],
  StormcallerChurchLuxRuins: [
    6300000,
    'Stormcaller Church, Lux Ruins',
    'AltusPlateau',
    true,
    false,
    false,
  ],
  TheShadedCastle: [
    6300001,
    'The Shaded Castle',
    'AltusPlateau',
    false,
    false,
    false,
  ],
  AltusHighwayJunction: [
    6300002,
    'Altus Highway Junction',
    'AltusPlateau',
    true,
    false,
    false,
  ],
  CastellansHall: [
    6300030,
    "Castellan's Hall",
    'AltusPlateau',
    false,
    false,
    false,
  ],
  ForestSpanningGreatbridge: [
    6300003,
    'Forest-Spanning Greatbridge',
    'AltusPlateau',
    true,
    false,
    false,
  ],
  UnsightlyCatacombs: [
    3012001,
    'Unsightly Catacombs',
    'AltusPlateau',
    false,
    true,
    false,
  ],
  SaintedHerosGrave: [
    3008001,
    "Sainted Hero's Grave",
    'AltusPlateau',
    false,
    true,
    false,
  ],
  SagesCave: [3119001, "Sage's Cave", 'AltusPlateau', false, true, false],
  PerfumersGrotto: [
    3118001,
    "Perfumer's Grotto",
    'AltusPlateau',
    false,
    true,
    false,
  ],
  DominulaWindmillVillageRoadofIniquitySidePath: [
    6300004,
    'Dominula, Windmill Village, Road of Iniquity Side Path',
    'AltusPlateau',
    true,
    false,
    false,
  ],
  OldAltusTunnel: [
    3204001,
    'Old Altus Tunnel',
    'AltusPlateau',
    false,
    true,
    false,
  ],
  AltusTunnel: [3205001, 'Altus Tunnel', 'AltusPlateau', false, true, false],

  NinthMtGelmirCampsite: [
    6302000,
    'Ninth Mt. Gelmir Campsite',
    'MtGelmir',
    true,
    false,
    false,
  ],
  RoadofIniquity: [6302001, 'Road of Iniquity', 'MtGelmir', true, false, false],
  SeethewaterTerminusPrimevalSorcererAzur: [
    6302002,
    'Seethewater Terminus, Primeval Sorcerer Azur',
    'MtGelmir',
    true,
    false,
    false,
  ],
  WyndhamCatacombs: [
    3007001,
    'Wyndham Catacombs',
    'MtGelmir',
    false,
    true,
    false,
  ],
  GelmirHerosGrave: [
    3009001,
    "Gelmir Hero's Grave",
    'MtGelmir',
    false,
    true,
    false,
  ],
  SeethewaterCave: [
    3107001,
    'Seethewater Cave',
    'MtGelmir',
    false,
    true,
    false,
  ],
  VolcanoCave: [3109001, 'Volcano Cave', 'MtGelmir', false, true, false],

  CapitalOutskirts: [
    6301000,
    'Capital Outskirts',
    'CapitalOutskirts',
    true,
    false,
    false,
  ],
  CapitalRampart: [
    6301090,
    'Capital Rampart',
    'CapitalOutskirts',
    true,
    false,
    false,
  ],
  AurizaSideTomb: [
    3013091,
    'Auriza Side Tomb',
    'CapitalOutskirts',
    false,
    true,
    false,
  ],
  AurizaHerosGrave: [
    3010001,
    "Auriza Hero's Grave",
    'CapitalOutskirts',
    false,
    true,
    false,
  ],
  SealedTunnel: [
    3412011,
    'Sealed Tunnel',
    'CapitalOutskirts',
    false,
    true,
    false,
  ],
  DivineTowerofWestAltus: [
    3412090,
    'Divine Tower of West Altus',
    'CapitalOutskirts',
    false,
    false,
    false,
  ],

  VolcanoManor: [1600012, 'Volcano Manor', 'VolcanoManor', false, false, false],
  PrisonTownChurch: [
    1600014,
    'Prison Town Church',
    'VolcanoManor',
    false,
    false,
    false,
  ],
  TempleofEiglay: [
    1600010,
    'Temple of Eiglay',
    'VolcanoManor',
    false,
    false,
    false,
  ],
  GuestHall: [1600016, 'Guest Hall', 'VolcanoManor', false, false, false],
  AudiencePathway: [
    1600006,
    'Audience Pathway',
    'VolcanoManor',
    false,
    false,
    true,
  ],
  AbductorVirgin: [
    1600020,
    'Abductor Virgin',
    'VolcanoManor',
    false,
    true,
    false,
  ],
  SubterraneanInquisitionChamber: [
    1600022,
    'Subterranean Inquisition Chamber',
    'VolcanoManor',
    false,
    false,
    false,
  ],
  RykardLordofBlasphemy: [
    1600000,
    'Rykard, Lord of Blasphemy',
    'VolcanoManor',
    false,
    false,
    true,
  ],

  ErdtreeSanctuary: [
    1100010,
    'Erdtree Sanctuary',
    'LeyndellRoyalCapital',
    false,
    false,
    false,
  ],
  EastCapitalRampart: [
    1100012,
    'East Capital Rampart',
    'LeyndellRoyalCapital',
    false,
    false,
    false,
  ],
  LowerCapitalChurch: [
    1100015,
    'Lower Capital Church',
    'LeyndellRoyalCapital',
    false,
    false,
    false,
  ],
  AvenueBalcony: [
    1100013,
    'Avenue Balcony',
    'LeyndellRoyalCapital',
    false,
    false,
    false,
  ],
  QueensBedchamber: [
    1100001,
    "Queen's Bedchamber",
    'LeyndellRoyalCapital',
    false,
    false,
    true,
  ],
  WestCapitalRampartFortifiedManorFirstFloor: [
    1100016,
    'West Capital Rampart, Fortified Manor, First Floor',
    'LeyndellRoyalCapital',
    false,
    false,
    false,
  ],
  DivineBridge: [
    1100017,
    'Divine Bridge',
    'LeyndellRoyalCapital',
    false,
    false,
    false,
  ],
  EldenThrone: [
    1100000,
    'Elden Throne',
    'LeyndellRoyalCapital',
    false,
    false,
    true,
  ],

  UndergroundRoadside: [
    3500002,
    'Underground Roadside',
    'SubterraneanShunningGrounds',
    false,
    false,
    false,
  ],
  ForsakenDepths: [
    3500008,
    'Forsaken Depths',
    'SubterraneanShunningGrounds',
    false,
    false,
    true,
  ],
  LeyndellCatacombs: [
    3500010,
    'Leyndell Catacombs',
    'SubterraneanShunningGrounds',
    false,
    false,
    false,
  ],
  LeyndellCatacombsPartII: [
    3500011,
    'Leyndell Catacombs Part II',
    'SubterraneanShunningGrounds',
    false,
    false,
    false,
  ],
  FrenziedFlameProscription: [
    3500092,
    'Frenzied Flame Proscription',
    'SubterraneanShunningGrounds',
    false,
    false,
    false,
  ],
  CathedraloftheForsaken: [
    3500000,
    'Cathedral of the Forsaken',
    'SubterraneanShunningGrounds',
    false,
    false,
    false,
  ],

  LeyndellCapitalofAsh: [
    1105011,
    'Leyndell, Capital of Ash',
    'LeyndellAshenCapital',
    false,
    false,
    true,
  ],
  AshenQueensBedchamber: [
    1105001,
    "Queen's Bedchamber ",
    'LeyndellAshenCapital',
    false,
    false,
    true,
  ],
  AshenDivineBridge: [
    1105092,
    'Divine Bridge ',
    'LeyndellAshenCapital',
    false,
    false,
    false,
  ],
  AshenEldenThrone: [
    1105000,
    'Elden Throne ',
    'LeyndellAshenCapital',
    false,
    false,
    true,
  ],

  FracturedMarika: [
    1900000,
    'Fractured Marika',
    'StonePlatform',
    false,
    false,
    true,
  ],
  EldenBeast: [1900001, 'Elden Beast', 'StonePlatform', false, false, true],

  CentralCaelid: [6400001, 'Central Caelid', 'Caelid', true, false, false],
  CaelidNorth: [6400000, 'Caelid North', 'Caelid', true, false, false],
  ChamberOutsidethePlaza: [
    6400002,
    'Chamber Outside the Plaza',
    'Caelid',
    false,
    false,
    true,
  ],
  RedmaneCastlePlaza: [
    6400010,
    'Redmane Castle Plaza',
    'Caelid',
    false,
    false,
    false,
  ],
  StarscourgeRadahn: [
    6400040,
    'Starscourge Radahn',
    'Caelid',
    false,
    false,
    true,
  ],
  MinorErdtreeCatacombs: [
    3014001,
    'Minor Erdtree Catacombs',
    'Caelid',
    false,
    true,
    false,
  ],
  CaelidCatacombs: [3015001, 'Caelid Catacombs', 'Caelid', false, true, false],
  WarDeadCatacombs: [
    3016001,
    'War-Dead Catacombs',
    'Caelid',
    false,
    true,
    false,
  ],
  AbandonedCave: [3120001, 'Abandoned Cave', 'Caelid', false, true, false],
  GaolCave: [3121001, 'Gaol Cave', 'Caelid', false, true, false],
  GaelTunnel: [3207001, 'Gael Tunnel', 'Caelid', false, true, false],
  GaelTunnelPartII: [
    3207002,
    'Gael Tunnel Part II',
    'Caelid',
    false,
    true,
    false,
  ],
  RearGaelTunnelEntrance: [
    3207090,
    'Rear Gael Tunnel Entrance',
    'Caelid',
    false,
    true,
    false,
  ],
  SelliaCrystalTunnel: [
    3208001,
    'Sellia Crystal Tunnel',
    'Caelid',
    false,
    true,
    false,
  ],
  ChairCryptofSellia: [
    6400020,
    'Chair-Crypt of Sellia',
    'Caelid',
    true,
    false,
    false,
  ],

  SwampofAeonia: [
    6401000,
    'Swamp of Aeonia',
    'SwampOfAeonia',
    true,
    false,
    false,
  ],

  Dragonbarrow: [
    6402000,
    'Dragonbarrow',
    'GreyollsDragonbarrow',
    true,
    false,
    false,
  ],
  SelliaHideaway: [
    3111001,
    'Sellia Hideaway',
    'GreyollsDragonbarrow',
    true,
    false,
    false,
  ],
  DragonbarrowCave: [
    3110001,
    'Dragonbarrow Cave',
    'GreyollsDragonbarrow',
    true,
    false,
    false,
  ],
  BestialSanctum: [
    6402001,
    'Bestial Sanctum',
    'GreyollsDragonbarrow',
    true,
    false,
    false,
  ],
  DivineTowerofCaelidCenter: [
    3413003,
    'Divine Tower of Caelid: Center',
    'GreyollsDragonbarrow',
    false,
    false,
    false,
  ],
  DivineTowerofCaelidBasemenr: [
    3413013,
    'Divine Tower of Caelid: Basement',
    'GreyollsDragonbarrow',
    false,
    false,
    true,
  ],
  IsolatedDivineTower: [
    3415090,
    'Isolated Divine Tower',
    'GreyollsDragonbarrow',
    false,
    false,
    false,
  ],

  ForbiddenLands: [
    6500000,
    'Forbidden Lands',
    'ForbiddenLands',
    true,
    false,
    false,
  ],
  GrandLiftofRold: [
    6500090,
    'Grand Lift of Rold',
    'ForbiddenLands',
    true,
    false,
    false,
  ],
  HiddenPathtotheHaligtree: [
    3020001,
    'Hidden Path to the Haligtree',
    'ForbiddenLands',
    false,
    true,
    false,
  ],
  HiddenPathtotheHaligtreePartII: [
    3020002,
    'Hidden Path to the Haligtree Part II',
    'ForbiddenLands',
    false,
    true,
    false,
  ],
  DivineTowerofEastAltus: [
    3414011,
    'Divine Tower of East Altus',
    'ForbiddenLands',
    false,
    false,
    false,
  ],

  ZamorRuins: [
    6501000,
    'Zamor Ruins',
    'MountaintopsOfTheGiants',
    true,
    false,
    false,
  ],
  CentralMountaintops: [
    6501001,
    'Central Mountaintops',
    'MountaintopsOfTheGiants',
    true,
    false,
    false,
  ],
  CastleSol: [
    6501002,
    'Castle Sol',
    'MountaintopsOfTheGiants',
    true,
    false,
    false,
  ],
  SpiritcallersCave: [
    3122001,
    "Spiritcaller's Cave",
    'MountaintopsOfTheGiants',
    false,
    true,
    false,
  ],
  CastleSolMainGateChurchoftheEclipse: [
    6501003,
    'Castle Sol Main Gate, Church of the Eclipse',
    'MountaintopsOfTheGiants',
    true,
    false,
    false,
  ],
  CastleSolRooftop: [
    6501010,
    'Castle Sol Rooftop',
    'MountaintopsOfTheGiants',
    true,
    false,
    false,
  ],

  GiantsGravepostFootoftheForge: [
    6502000,
    "Giants' Gravepost, Foot of the Forge",
    'FlamePeak',
    false,
    false,
    true,
  ],
  FireGiant: [6502010, 'Fire Giant', 'FlamePeak', false, false, true],
  GiantsMountaintopCatacombs: [
    3018001,
    "Giants' Mountaintop Catacombs",
    'FlamePeak',
    false,
    true,
    false,
  ],
  GiantConqueringHerosGrave: [
    3017002,
    "Giant-Conquering Hero's Grave",
    'FlamePeak',
    false,
    true,
    false,
  ],

  ConsecratedSnowfield: [
    6503000,
    'Consecrated Snowfield',
    'ConsecratedSnowfield',
    true,
    false,
    false,
  ],
  ConsecratedSnowfieldCatacombs: [
    3019001,
    'Consecrated Snowfield Catacombs',
    'ConsecratedSnowfield',
    false,
    true,
    false,
  ],
  CaveoftheForlorn: [
    3112001,
    'Cave of the Forlorn',
    'ConsecratedSnowfield',
    false,
    true,
    false,
  ],
  YeloughAnixTunnel: [
    3211001,
    'Yelough Anix Tunnel',
    'ConsecratedSnowfield',
    false,
    true,
    false,
  ],

  HaligtreeCanopy: [
    1500011,
    'Haligtree Canopy',
    'MiquellasHaligtree',
    false,
    false,
    false,
  ],
  HaligtreeTownPlaza: [
    1500012,
    'Haligtree Town Plaza',
    'MiquellasHaligtree',
    false,
    false,
    true,
  ],
  HaligtreePromenade: [
    1500010,
    'Haligtree Promenade',
    'MiquellasHaligtree',
    false,
    false,
    true,
  ],

  PrayerRoom: [
    1500001,
    'Prayer Room',
    'ElphaelBraceOfTheHaligtree',
    false,
    false,
    false,
  ],
  ElphaelInnerWallDrainageChannel: [
    1500002,
    'Elphael Inner Wall, Drainage Channel',
    'ElphaelBraceOfTheHaligtree',
    false,
    false,
    false,
  ],
  HaligtreeRoots: [
    1500003,
    'Haligtree Roots',
    'ElphaelBraceOfTheHaligtree',
    false,
    false,
    true,
  ],
  MaleniaGoddessofRot: [
    1500000,
    'Malenia, Goddess of Rot',
    'ElphaelBraceOfTheHaligtree',
    false,
    false,
    true,
  ],

  AinselRiverWellDepths: [
    1201001,
    'Ainsel River Well Depths',
    'AinselRiver',
    false,
    false,
    false,
  ],
  AinselRiverDownstream: [
    1201002,
    'Ainsel River Downstream',
    'AinselRiver',
    false,
    false,
    false,
  ],
  AinselRiverDownstreamPartII: [
    1201003,
    'Ainsel River Downstream Part II',
    'AinselRiver',
    false,
    false,
    false,
  ],
  AstelNaturalbornoftheVoid: [
    1204000,
    'Astel, Naturalborn of the Void',
    'AinselRiver',
    false,
    false,
    true,
  ],
  DragonkinSoldierofNokstella: [
    1201000,
    'Dragonkin Soldier of Nokstella',
    'AinselRiver',
    false,
    false,
    false,
  ],

  AinselRiverMain: [
    1201011,
    'Ainsel River Main',
    'AinselRiverMain',
    false,
    false,
    false,
  ],
  NokstellaEternalCity: [
    1201013,
    'Nokstella, Eternal City',
    'AinselRiverMain',
    false,
    false,
    false,
  ],
  NokstellaWaterfallBasin: [
    1201014,
    'Nokstella Waterfall Basin',
    'AinselRiverMain',
    false,
    false,
    false,
  ],

  LakeofRotShoreside: [
    1201015,
    'Lake of Rot Shoreside',
    'LakeOfRot',
    false,
    false,
    false,
  ],
  GrandCloister: [1201016, 'Grand Cloister', 'LakeOfRot', false, false, false],
  GrandCloisterPartII: [
    1201017,
    'Grand Cloister Part II',
    'LakeOfRot',
    false,
    false,
    false,
  ],

  NokronEternalCity: [
    1207026,
    'Nokron, Eternal City',
    'NokronEternalCity',
    false,
    false,
    false,
  ],
  MimicTear: [1202020, 'Mimic Tear', 'NokronEternalCity', false, false, false],
  AncestralWoods: [
    1202002,
    'Ancestral Woods',
    'NokronEternalCity',
    false,
    false,
    false,
  ],
  NightsSacredGround: [
    1202007,
    "Night's Sacred Ground",
    'NokronEternalCity',
    false,
    false,
    false,
  ],
  AqueductFacingCliffs: [
    1202003,
    'Aqueduct-Facing Cliffs',
    'NokronEternalCity',
    false,
    false,
    false,
  ],
  AqueductFacingCliffsPartII: [
    1202004,
    'Aqueduct-Facing Cliffs Part II',
    'NokronEternalCity',
    false,
    false,
    true,
  ],
  GreatWaterfallBasin: [
    1202000,
    'Great Waterfall Basin',
    'NokronEternalCity',
    false,
    false,
    true,
  ],

  PalaceApproachLedgeRoad: [
    1205001,
    'Palace Approach Ledge-Road',
    'MohgwynPalace',
    false,
    false,
    false,
  ],
  DynastyMausoleumEntrance: [
    1205004,
    'Dynasty Mausoleum Entrance',
    'MohgwynPalace',
    false,
    false,
    false,
  ],
  DynastyMausoleumMidpoint: [
    1205006,
    'Dynasty Mausoleum Midpoint',
    'MohgwynPalace',
    false,
    false,
    true,
  ],
  CocoonoftheEmpyrean: [
    1205000,
    'Cocoon of the Empyrean',
    'MohgwynPalace',
    false,
    false,
    true,
  ],

  SiofraRiverWellDepths: [
    1207031,
    'Siofra River Well Depths',
    'SiofraRiver',
    false,
    false,
    false,
  ],
  SiofraRiverBank: [
    1202033,
    'Siofra River Bank',
    'SiofraRiver',
    false,
    false,
    false,
  ],
  WorshippersWoods: [
    1202034,
    "Worshippers' Woods",
    'SiofraRiver',
    false,
    false,
    false,
  ],

  RootFacingCliffs: [
    1203001,
    'Root-Facing Cliffs',
    'DeeprootDepths',
    false,
    false,
    false,
  ],
  GreatWaterfallCrestPartII: [
    1203002,
    'Great Waterfall Crest Part II',
    'DeeprootDepths',
    false,
    false,
    false,
  ],
  DeeprootDepths: [
    1203003,
    'Deeproot Depths',
    'DeeprootDepths',
    false,
    false,
    false,
  ],
  TheNamelessEternalCity: [
    1203004,
    'The Nameless Eternal City',
    'DeeprootDepths',
    false,
    false,
    false,
  ],
  AcrosstheRoots: [
    1203005,
    'Across the Roots',
    'DeeprootDepths',
    false,
    false,
    true,
  ],
  PrinceofDeathsThrone: [
    1203000,
    "Prince of Death's Throne",
    'DeeprootDepths',
    false,
    false,
    true,
  ],

  CrumblingBeastGrave: [
    1300012,
    'Crumbling Beast Grave',
    'CrumblingFarumAzula',
    false,
    false,
    false,
  ],
  CrumblingBeastGraveDepthsTempestFacingBalcony: [
    1300013,
    'Crumbling Beast Grave Depths, Tempest-Facing Balcony',
    'CrumblingFarumAzula',
    false,
    false,
    false,
  ],
  DragonTemple: [
    1300017,
    'Dragon Temple',
    'CrumblingFarumAzula',
    false,
    false,
    true,
  ],
  DragonTempleTransept: [
    1300018,
    'Dragon Temple Transept',
    'CrumblingFarumAzula',
    false,
    false,
    true,
  ],
  DragonTempleAltar: [
    1300010,
    'Dragon Temple Altar',
    'CrumblingFarumAzula',
    false,
    false,
    true,
  ],
  DragonTempleLift: [
    1300019,
    'Dragon Temple Lift',
    'CrumblingFarumAzula',
    false,
    false,
    false,
  ],
  DragonTempleRooftop: [
    1300003,
    'Dragon Temple Rooftop',
    'CrumblingFarumAzula',
    false,
    false,
    false,
  ],
  DragonlordPlacidusax: [
    1300020,
    'Dragonlord Placidusax',
    'CrumblingFarumAzula',
    false,
    false,
    true,
  ],
  BesidetheGreatBridge: [
    1300006,
    'Beside the Great Bridge',
    'CrumblingFarumAzula',
    false,
    false,
    true,
  ],
  MalikeththeBlackBlade: [
    1300000,
    'Maliketh, the Black Blade',
    'CrumblingFarumAzula',
    false,
    false,
    true,
  ],
};
