import { Effect } from 'effect';

import type { BossArea } from '../game/bosses.ts';
import type { Grace } from '../game/graces.ts';
import type { ItemText } from '../game/item-text.ts';
import type { MapEntity } from '../game/map-markers.ts';
import type {
  ArmorRecord,
  AshOfWarRecord,
  GoodRecord,
  TalismanRecord,
  WeaponRecord,
} from './join.ts';

/**
 * Stage 8 — codegen. Writes the extracted datasets as typed `.ts` files into the
 * `@elden-ring-compass/data` workspace package (`packages/elden-ring-data/src/
 * generated/`) — the single source of truth the web app depends on. Output is
 * deterministic (stable sort, fixed field order) so re-running on an unchanged
 * install produces an identical diff-free tree. The legacy hand/erdb files under
 * apps/web stay until the app is migrated to consume this package.
 */

export interface CodegenInput {
  readonly graces: readonly Grace[];
  readonly bosses: readonly BossArea[];
  readonly weapons: readonly WeaponRecord[];
  readonly armor: readonly ArmorRecord[];
  readonly talismans: readonly TalismanRecord[];
  readonly goods: readonly GoodRecord[];
  readonly ashesOfWar: readonly AshOfWarRecord[];
  readonly markers: readonly MapEntity[];
  // Name tables for the remaining categories without a decoded stat record
  // (weapon arts) — emitted as {id, name}.
  readonly names: ItemText;
}

interface NamedRecord {
  readonly id: number;
  readonly name: string;
}

/** Sorted {id, name} rows from a name FMG map, dropping blank/[ERROR] entries. */
const nameRows = (table: ReadonlyMap<number, string>): NamedRecord[] =>
  [...table.entries()]
    .filter(([, n]) => n.trim().length > 0 && n !== '[ERROR]')
    .map(([id, name]) => ({ id, name }))
    .sort((a, b) => a.id - b.id);

// The generated package lives next to er-extractor in the monorepo; resolve it
// from this module so the output dir is independent of the process cwd.
const GENERATED_DIR = new URL(
  '../../../elden-ring-data/src/generated/',
  import.meta.url,
);

const HEADER =
  '// @generated by @elden-ring-compass/er-extractor — do not edit by hand.\n' +
  '// Regenerate with `bun run extract` against an Elden Ring install.\n\n';

/** Render `export interface <type> { … }` + `export const <name>: readonly <type>[]`. */
const renderDataset = (
  typeName: string,
  fields: readonly string[],
  constName: string,
  rows: readonly object[],
): string => {
  const iface = `export interface ${typeName} {\n${fields.map((f) => `  ${f}`).join('\n')}\n}\n\n`;
  const body = rows.map((r) => `  ${JSON.stringify(r)},`).join('\n');
  return `${HEADER}${iface}export const ${constName}: readonly ${typeName}[] = [\n${body}\n];\n`;
};

const write = (fileName: string, contents: string) =>
  Effect.tryPromise(() =>
    Bun.write(new URL(fileName, GENERATED_DIR), contents),
  );

export const codegen = (input: CodegenInput) =>
  Effect.gen(function* () {
    // Sort each dataset by a stable key for deterministic, diff-friendly output.
    const graces = [...input.graces].sort((a, b) => a.flagId - b.flagId);
    const bosses = [...input.bosses].sort(
      (a, b) => a.defeatFlagId - b.defeatFlagId,
    );
    const weapons = [...input.weapons].sort((a, b) => a.id - b.id);
    const markers = [...input.markers].sort(
      (a, b) => a.mapId.localeCompare(b.mapId) || a.entityID - b.entityID,
    );

    yield* write(
      'graces.ts',
      renderDataset(
        'Grace',
        [
          'readonly flagId: number;',
          'readonly name: string;',
          'readonly region: string | null;',
          'readonly bonfireEntityId: number;',
          'readonly mapArea: number;',
        ],
        'GRACES',
        graces.map((g) => ({
          flagId: g.flagId,
          name: g.name,
          region: g.region,
          bonfireEntityId: g.bonfireEntityId,
          mapArea: g.areaNo,
        })),
      ),
    );

    yield* write(
      'bosses.ts',
      renderDataset(
        'Boss',
        [
          'readonly defeatFlagId: number;',
          'readonly name: string | null;',
          'readonly mapId: string;',
          'readonly x: number;',
          'readonly y: number;',
          'readonly z: number;',
        ],
        'BOSSES',
        bosses.map((b) => ({
          defeatFlagId: b.defeatFlagId,
          name: b.name,
          mapId: b.mapId,
          x: b.x,
          y: b.y,
          z: b.z,
        })),
      ),
    );

    yield* write(
      'weapons.ts',
      renderDataset(
        'Weapon',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly category: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly attackPhysical: number;',
          'readonly reqStrength: number;',
          'readonly reqDexterity: number;',
          'readonly reqIntelligence: number;',
          'readonly reqFaith: number;',
          'readonly reqArcane: number;',
          'readonly effects: readonly { readonly attribute: string; readonly value: number; readonly model: string; readonly type: string; readonly conditions?: readonly string[] }[];',
        ],
        'WEAPONS',
        weapons.map((w) => ({ ...w })),
      ),
    );

    const armor = [...input.armor].sort((a, b) => a.id - b.id);
    yield* write(
      'armor.ts',
      renderDataset(
        'Armor',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly negationPhysical: number;',
          'readonly negationStrike: number;',
          'readonly negationSlash: number;',
          'readonly negationPierce: number;',
          'readonly negationMagic: number;',
          'readonly negationFire: number;',
          'readonly negationLightning: number;',
          'readonly negationHoly: number;',
          'readonly resistPoison: number;',
          'readonly resistScarletRot: number;',
          'readonly resistBleed: number;',
          'readonly resistFrost: number;',
          'readonly resistSleep: number;',
          'readonly resistMadness: number;',
          'readonly resistDeath: number;',
          'readonly poise: number;',
          'readonly effects: readonly { readonly attribute: string; readonly value: number; readonly model: string; readonly type: string; readonly conditions?: readonly string[] }[];',
        ],
        'ARMOR',
        armor.map((a) => ({ ...a })),
      ),
    );

    const talismans = [...input.talismans].sort((a, b) => a.id - b.id);
    yield* write(
      'talismans.ts',
      renderDataset(
        'Talisman',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly conflicts: readonly string[];',
          'readonly effects: readonly { readonly attribute: string; readonly value: number; readonly model: string; readonly type: string; readonly conditions?: readonly string[] }[];',
        ],
        'TALISMANS',
        talismans.map((t) => ({ ...t })),
      ),
    );

    // Goods (consumables, materials, spells, spirit ashes, key items, …) — one
    // table tagged with a derived category from EquipParamGoods.goodsType.
    const goods = [...input.goods].sort((a, b) => a.id - b.id);
    yield* write(
      'goods.ts',
      renderDataset(
        'Good',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly category: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly maxHeld: number;',
        ],
        'GOODS',
        goods.map((g) => ({ ...g })),
      ),
    );

    const ashesOfWar = [...input.ashesOfWar].sort((a, b) => a.id - b.id);
    yield* write(
      'ashes-of-war.ts',
      renderDataset(
        'AshOfWar',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly armamentCategories: readonly string[];',
          'readonly defaultAffinity: string;',
          'readonly possibleAffinities: readonly string[];',
          'readonly skillId: number;',
        ],
        'ASHES_OF_WAR',
        ashesOfWar.map((a) => ({ ...a })),
      ),
    );

    // Weapon arts have no decoded stat record yet; emit as {id, name} (base + DLC).
    const nameTables: readonly [
      string,
      string,
      string,
      ReadonlyMap<number, string>,
    ][] = [['arts.ts', 'WeaponArt', 'ARTS', input.names.ArtsName]];
    const nameFields = ['readonly id: number;', 'readonly name: string;'];
    for (const [file, typeName, constName, table] of nameTables) {
      yield* write(
        file,
        renderDataset(typeName, nameFields, constName, nameRows(table)),
      );
    }

    yield* write(
      'markers.ts',
      renderDataset(
        'MapMarker',
        [
          'readonly mapId: string;',
          // kind is 'part' | 'region' but typed `string`: a literal union over
          // ~24k rows overflows the type checker (TS2590).
          'readonly kind: string;',
          'readonly type: number;',
          'readonly name: string;',
          'readonly entityId: number;',
          'readonly x: number;',
          'readonly y: number;',
          'readonly z: number;',
          'readonly npcParamId: number | null;',
        ],
        'MAP_MARKERS',
        markers.map((m) => ({
          mapId: m.mapId,
          kind: m.kind,
          type: m.type,
          name: m.name,
          entityId: m.entityID,
          x: m.x,
          y: m.y,
          z: m.z,
          npcParamId: m.npcParamId,
        })),
      ),
    );

    const modules = [
      'graces',
      'bosses',
      'weapons',
      'armor',
      'talismans',
      'ashes-of-war',
      'goods',
      'arts',
      'markers',
    ];
    const index =
      HEADER +
      modules.map((m) => `export * from './${m}.ts';`).join('\n') +
      '\n';
    yield* write('index.ts', index);

    yield* Effect.logInfo(
      `codegen → @elden-ring-compass/data: ${graces.length} graces, ${bosses.length} bosses, ` +
        `${weapons.length} weapons, ${armor.length} armor, ${talismans.length} talismans, ` +
        `${goods.length} goods, ${ashesOfWar.length} ashes of war, ${markers.length} markers ` +
        `(+ arts name table)`,
    );
  });
