import { Effect, FileSystem, Path } from 'effect';

import type { Archetype } from '../game/archetypes.ts';
import type { BossArea } from '../game/bosses.ts';
import { loadEventFlagBst } from '../game/event-flags.ts';
import type { Grace } from '../game/graces.ts';
import type { ItemText } from '../game/item-text.ts';
import type { MapFragment } from '../game/map-fragments.ts';
import type { Region } from '../game/regions.ts';
import type { ClassifiedMarker } from '../game/marker-classify.ts';
import type { Placement } from '../game/placements.ts';
import type {
  ArmorRecord,
  AshOfWarRecord,
  GoodRecord,
  SpellRecord,
  SpiritAshRecord,
  TalismanRecord,
  WeaponRecord,
} from './join.ts';

/**
 * Stage 9 — codegen. Writes the extracted datasets as typed `.ts` files into the
 * `@elden-ring-compass/data` workspace package (`packages/elden-ring-data/src/
 * generated/`) — the single source of truth the web app depends on. Output is
 * deterministic (stable sort, fixed field order) so re-running on an unchanged
 * install produces an identical diff-free tree. The legacy hand/erdb files under
 * apps/web stay until the app is migrated to consume this package.
 */

export interface CodegenInput {
  readonly graces: readonly Grace[];
  readonly bosses: readonly BossArea[];
  readonly regions: readonly Region[];
  readonly matchmakingRegionIds: readonly number[];
  readonly mapFragments: readonly MapFragment[];
  readonly archetypes: readonly Archetype[];
  readonly weapons: readonly WeaponRecord[];
  readonly armor: readonly ArmorRecord[];
  readonly talismans: readonly TalismanRecord[];
  readonly goods: readonly GoodRecord[];
  readonly ashesOfWar: readonly AshOfWarRecord[];
  readonly spells: readonly SpellRecord[];
  readonly spiritAshes: readonly SpiritAshRecord[];
  readonly markers: readonly ClassifiedMarker[];
  readonly placements: readonly Placement[];
  // Name tables for the remaining categories without a decoded stat record
  // (weapon arts) — emitted as {id, name}.
  readonly names: ItemText;
}

interface NamedRecord {
  readonly id: number;
  readonly name: string;
}

/** Sorted {id, name} rows from a name FMG map, dropping blank/[ERROR] entries. */
const nameRows = (table: ReadonlyMap<number, string>): NamedRecord[] =>
  [...table.entries()]
    .filter(([, n]) => n.trim().length > 0 && n !== '[ERROR]')
    .map(([id, name]) => ({ id, name }))
    .sort((a, b) => a.id - b.id);

// The generated package lives next to er-extractor in the monorepo; resolve it
// from this module so the output dir is independent of the process cwd.
const GENERATED_DIR = new URL(
  '../../../elden-ring-data/src/generated/',
  import.meta.url,
);

const HEADER =
  '// @generated by @elden-ring-compass/er-extractor — do not edit by hand.\n' +
  '// Regenerate with `bun run extract` against an Elden Ring install.\n\n';

/** Render `export interface <type> { … }` + `export const <name>: readonly <type>[]`. */
const renderDataset = (
  typeName: string,
  fields: readonly string[],
  constName: string,
  rows: readonly object[],
): string => {
  const iface = `export interface ${typeName} {\n${fields.map((f) => `  ${f}`).join('\n')}\n}\n\n`;
  const body = rows.map((r) => `  ${JSON.stringify(r)},`).join('\n');
  return `${HEADER}${iface}export const ${constName}: readonly ${typeName}[] = [\n${body}\n];\n`;
};

const write = (fileName: string, contents: string) =>
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const filePath = yield* path.fromFileUrl(new URL(fileName, GENERATED_DIR));
    yield* fs.writeFileString(filePath, contents);
  });

/** Emit the event-flag addressing table + `eventFlagOffset()` reader (hand-shaped code). */
const renderEventFlags = (
  bst: ReadonlyArray<readonly [number, number]>,
): string =>
  `${HEADER}// Event-flag block → byte-offset multiplier (vendored ER-Save-Lib eventflag_bst).\n` +
  `export const EVENT_FLAG_BST: ReadonlyMap<number, number> = new Map([\n` +
  `${bst.map(([b, m]) => `  [${b}, ${m}],`).join('\n')}\n]);\n\n` +
  `/**\n` +
  ` * Resolve an event-flag id to its [byteOffset, bitPos] in the save's event-flag\n` +
  ` * bitfield. Returns null for an unknown block. (ER-Save-Lib formula.)\n` +
  ` */\n` +
  `export function eventFlagOffset(\n  id: number,\n): readonly [number, number] | null {\n` +
  `  const mult = EVENT_FLAG_BST.get(Math.floor(id / 1000));\n` +
  `  if (mult === undefined) return null;\n` +
  `  const index = id % 1000;\n` +
  `  return [mult * 125 + Math.floor(index / 8), 7 - (index % 8)];\n` +
  `}\n`;

/**
 * Render `generated/regions.ts` — the `REGIONS` table plus the `MATCHMAKING_REGION_IDS`
 * ignore-set. Self-contained (sorts its own inputs) so it can be regenerated in isolation.
 */
export const renderRegionsFile = (
  regionsInput: readonly Region[],
  matchmakingRegionIdsInput: readonly number[],
): string => {
  const regions = [...regionsInput].sort((a, b) => a.id - b.id);
  const matchmakingIds = [...matchmakingRegionIdsInput].sort((a, b) => a - b);
  // Pack the matchmaking ids 12-per-line so the Set stays readable in diffs.
  const matchmakingLines: string[] = [];
  for (let i = 0; i < matchmakingIds.length; i += 12) {
    matchmakingLines.push(
      '  ' + matchmakingIds.slice(i, i + 12).join(', ') + ',',
    );
  }
  return (
    renderDataset(
      'Region',
      [
        'readonly id: number;',
        'readonly name: string;',
        'readonly area: string | null;',
        'readonly isOpenWorld: boolean;',
        'readonly isDungeon: boolean;',
      ],
      'REGIONS',
      regions.map((r) => ({ ...r })),
    ) +
    '\n// areaNo==0 PlayRegionParam rowIds — multiplayer/invasion matchmaking siblings of placed\n' +
    "// regions. The game activates these as the player moves, so they appear in the save's\n" +
    '// unlocked_regions, but they have no name/placement and are NOT user-facing places.\n' +
    'export const MATCHMAKING_REGION_IDS: ReadonlySet<number> = new Set([\n' +
    `${matchmakingLines.join('\n')}\n]);\n`
  );
};

/** Render `generated/markers.ts` — classified MSB entities. Self-contained (sorts its inputs). */
export const renderMarkersFile = (
  markersInput: readonly ClassifiedMarker[],
): string => {
  const markers = [...markersInput].sort(
    (a, b) => a.mapId.localeCompare(b.mapId) || a.entityID - b.entityID,
  );
  return renderDataset(
    'MapMarker',
    [
      'readonly mapId: string;',
      // kind is 'part' | 'region' but typed `string`: a literal union over
      // ~24k rows overflows the type checker (TS2590). Same for `category`.
      'readonly kind: string;',
      'readonly type: number;',
      'readonly category: string;',
      'readonly name: string;',
      'readonly displayName: string | null;',
      'readonly entityId: number;',
      'readonly x: number;',
      'readonly y: number;',
      'readonly z: number;',
      'readonly npcParamId: number | null;',
    ],
    'MAP_MARKERS',
    markers.map((m) => ({
      mapId: m.mapId,
      kind: m.kind,
      type: m.type,
      category: m.category,
      name: m.name,
      displayName: m.displayName,
      entityId: m.entityID,
      x: m.x,
      y: m.y,
      z: m.z,
      npcParamId: m.npcParamId,
    })),
  );
};

/** Render `generated/placements.ts` — item world-placements. Self-contained (sorts its inputs). */
export const renderPlacementsFile = (
  placementsInput: readonly Placement[],
): string => {
  const placements = [...placementsInput].sort(
    (a, b) =>
      a.mapId.localeCompare(b.mapId) ||
      a.entityId - b.entityId ||
      a.itemId - b.itemId,
  );
  return renderDataset(
    'Placement',
    [
      'readonly mapId: string;',
      'readonly entityId: number;',
      'readonly x: number;',
      'readonly y: number;',
      'readonly z: number;',
      'readonly npcParamId: number;',
      'readonly lotId: number;',
      'readonly itemId: number;',
      'readonly itemType: string;',
      'readonly quantity: number;',
      'readonly chance: number;',
      'readonly source: string;',
    ],
    'PLACEMENTS',
    placements.map((p) => ({ ...p })),
  );
};

export const codegen = (input: CodegenInput) =>
  Effect.gen(function* () {
    // Sort each dataset by a stable key for deterministic, diff-friendly output.
    const graces = [...input.graces].sort((a, b) => a.flagId - b.flagId);
    const bosses = [...input.bosses].sort(
      (a, b) => a.defeatFlagId - b.defeatFlagId,
    );
    const weapons = [...input.weapons].sort((a, b) => a.id - b.id);

    yield* write(
      'graces.ts',
      renderDataset(
        'Grace',
        [
          'readonly flagId: number;',
          'readonly name: string;',
          'readonly region: string | null;',
          'readonly bonfireEntityId: number;',
          'readonly mapArea: number;',
        ],
        'GRACES',
        graces.map((g) => ({
          flagId: g.flagId,
          name: g.name,
          region: g.region,
          bonfireEntityId: g.bonfireEntityId,
          mapArea: g.areaNo,
        })),
      ),
    );

    yield* write(
      'bosses.ts',
      renderDataset(
        'Boss',
        [
          'readonly defeatFlagId: number;',
          'readonly name: string | null;',
          'readonly mapId: string;',
          'readonly x: number;',
          'readonly y: number;',
          'readonly z: number;',
        ],
        'BOSSES',
        bosses.map((b) => ({
          defeatFlagId: b.defeatFlagId,
          name: b.name,
          mapId: b.mapId,
          x: b.x,
          y: b.y,
          z: b.z,
        })),
      ),
    );

    yield* write(
      'weapons.ts',
      renderDataset(
        'Weapon',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly category: string;',
          'readonly allowAshOfWar: boolean;',
          'readonly isBuffable: boolean;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly attackPhysical: number;',
          'readonly reqStrength: number;',
          'readonly reqDexterity: number;',
          'readonly reqIntelligence: number;',
          'readonly reqFaith: number;',
          'readonly reqArcane: number;',
          'readonly upgradeMaterial: string;',
          'readonly upgradeCosts: readonly number[];',
          'readonly effects: readonly { readonly attribute: string; readonly value: number; readonly model: string; readonly type: string; readonly conditions?: readonly string[] }[];',
        ],
        'WEAPONS',
        weapons.map((w) => ({ ...w })),
      ),
    );

    const armor = [...input.armor].sort((a, b) => a.id - b.id);
    yield* write(
      'armor.ts',
      renderDataset(
        'Armor',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly category: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly negationPhysical: number;',
          'readonly negationStrike: number;',
          'readonly negationSlash: number;',
          'readonly negationPierce: number;',
          'readonly negationMagic: number;',
          'readonly negationFire: number;',
          'readonly negationLightning: number;',
          'readonly negationHoly: number;',
          'readonly resistPoison: number;',
          'readonly resistScarletRot: number;',
          'readonly resistBleed: number;',
          'readonly resistFrost: number;',
          'readonly resistSleep: number;',
          'readonly resistMadness: number;',
          'readonly resistDeath: number;',
          'readonly poise: number;',
          'readonly effects: readonly { readonly attribute: string; readonly value: number; readonly model: string; readonly type: string; readonly conditions?: readonly string[] }[];',
        ],
        'ARMOR',
        armor.map((a) => ({ ...a })),
      ),
    );

    const talismans = [...input.talismans].sort((a, b) => a.id - b.id);
    yield* write(
      'talismans.ts',
      renderDataset(
        'Talisman',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly conflicts: readonly string[];',
          'readonly effects: readonly { readonly attribute: string; readonly value: number; readonly model: string; readonly type: string; readonly conditions?: readonly string[] }[];',
        ],
        'TALISMANS',
        talismans.map((t) => ({ ...t })),
      ),
    );

    // Goods (consumables, materials, spells, spirit ashes, key items, …) — one
    // table tagged with a derived category from EquipParamGoods.goodsType.
    const goods = [...input.goods].sort((a, b) => a.id - b.id);
    yield* write(
      'goods.ts',
      renderDataset(
        'Good',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly category: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly weight: number;',
          'readonly maxHeld: number;',
        ],
        'GOODS',
        goods.map((g) => ({ ...g })),
      ),
    );

    const ashesOfWar = [...input.ashesOfWar].sort((a, b) => a.id - b.id);
    yield* write(
      'ashes-of-war.ts',
      renderDataset(
        'AshOfWar',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly armamentCategories: readonly string[];',
          'readonly defaultAffinity: string;',
          'readonly possibleAffinities: readonly string[];',
          'readonly skillId: number;',
        ],
        'ASHES_OF_WAR',
        ashesOfWar.map((a) => ({ ...a })),
      ),
    );

    const spells = [...input.spells].sort((a, b) => a.id - b.id);
    yield* write(
      'spells.ts',
      renderDataset(
        'Spell',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly category: string;',
          'readonly fpCost: number;',
          'readonly fpCostExtra: number;',
          'readonly spCost: number;',
          'readonly slotsUsed: number;',
          'readonly reqIntelligence: number;',
          'readonly reqFaith: number;',
          'readonly reqArcane: number;',
          'readonly isWeaponBuff: boolean;',
        ],
        'SPELLS',
        spells.map((s) => ({ ...s })),
      ),
    );

    const spiritAshes = [...input.spiritAshes].sort((a, b) => a.id - b.id);
    yield* write(
      'spirit-ashes.ts',
      renderDataset(
        'SpiritAsh',
        [
          'readonly id: number;',
          'readonly name: string;',
          'readonly summary: string;',
          'readonly description: readonly string[];',
          'readonly rarity: string;',
          'readonly icon: number;',
          'readonly sellValue: number;',
          'readonly summonName: string;',
          'readonly fpCost: number;',
          'readonly hpCost: number;',
          'readonly upgradeMaterial: string;',
          'readonly upgradeCosts: readonly number[];',
        ],
        'SPIRIT_ASHES',
        spiritAshes.map((s) => ({ ...s })),
      ),
    );

    // Weapon arts have no decoded stat record yet; emit as {id, name} (base + DLC).
    const nameTables: readonly [
      string,
      string,
      string,
      ReadonlyMap<number, string>,
    ][] = [['arts.ts', 'WeaponArt', 'ARTS', input.names.ArtsName]];
    const nameFields = ['readonly id: number;', 'readonly name: string;'];
    for (const [file, typeName, constName, table] of nameTables) {
      yield* write(
        file,
        renderDataset(typeName, nameFields, constName, nameRows(table)),
      );
    }

    yield* write('markers.ts', renderMarkersFile(input.markers));

    yield* write('placements.ts', renderPlacementsFile(input.placements));

    yield* write(
      'regions.ts',
      renderRegionsFile(input.regions, input.matchmakingRegionIds),
    );

    const mapFragments = [...input.mapFragments].sort(
      (a, b) => a.openEventFlagId - b.openEventFlagId,
    );
    yield* write(
      'map-fragments.ts',
      renderDataset(
        'MapFragment',
        [
          'readonly pieceId: number;',
          'readonly openEventFlagId: number;',
          'readonly acquisitionEventFlagId: number;',
          'readonly name: string | null;',
          'readonly areaNo: number;',
          'readonly gridX: number;',
          'readonly gridZ: number;',
        ],
        'MAP_FRAGMENTS',
        mapFragments.map((m) => ({ ...m })),
      ),
    );

    const archetypes = [...input.archetypes].sort((a, b) => a.id - b.id);
    yield* write(
      'archetypes.ts',
      renderDataset(
        'Archetype',
        ['readonly id: number;', 'readonly name: string;'],
        'ARCHETYPES',
        archetypes.map((a) => ({ ...a })),
      ),
    );

    yield* write('event-flags.ts', renderEventFlags(yield* loadEventFlagBst));

    const modules = [
      'graces',
      'bosses',
      'weapons',
      'armor',
      'talismans',
      'ashes-of-war',
      'goods',
      'spells',
      'spirit-ashes',
      'arts',
      'regions',
      'map-fragments',
      'archetypes',
      'markers',
      'placements',
      'event-flags',
    ];
    const index =
      HEADER +
      modules.map((m) => `export * from './${m}.ts';`).join('\n') +
      '\n';
    yield* write('index.ts', index);

    yield* Effect.logInfo(
      `codegen → @elden-ring-compass/data: ${graces.length} graces, ${bosses.length} bosses, ` +
        `${weapons.length} weapons, ${armor.length} armor, ${talismans.length} talismans, ` +
        `${goods.length} goods, ${ashesOfWar.length} ashes of war, ${spells.length} spells, ` +
        `${spiritAshes.length} spirit ashes, ${mapFragments.length} map fragments, ` +
        `${input.markers.length} markers, ${input.placements.length} placements (+ arts name table)`,
    );
  });
